import type { GameScript } from '../types'

/**
 * U12・1試合（4Q）のゲーム台本（白=Aチーム / 赤=Bチーム）。
 * 根拠: knowledge/08-to-scoresheet（記入・APアロー）、knowledge/09-to-timer-shotclock（SC判断）
 * ゲームクロック整合・SC切れ・ファウル枠・得点累計・ペン色・記号カバレッジは
 * validate-content が機械検証する。
 * 白: 4(→10と交代), 5, 6, 7, 8 ／ 赤: 4, 5, 6, 9, 11
 */
export const gameU12Script: GameScript = {
  id: 'sim-game-u12',
  title: '1試合通しプレイ（U12）',
  description:
    'ジャンプボールからゲーム終了まで、U12の1試合（6分×4Q）をイベントごとに判断。自分の役割の仕事を1つずつ答え合わせしながら進める。',
  ruleset: 'u12',
  quarterMs: 360000,
  ruleYear: 2026,
  events: [
    // ================= 第1Q（赤ペン）: 基本のFG/FT・P・タイムアウト・アロー =================
    {
      id: 'ev-001',
      quarter: 1,
      gameClockMs: 360000,
      type: 'periodStart',
      narration:
        'ジャンプボール！トスが上がり、白7番がタップして白チームが最初のコントロール。第1Qスタート！',
      team: 'A',
      playerNo: 7,
      shot: 24,
      expect: {
        'sc-operator': {
          action: 'reset24',
          explanation:
            'ジャンプボールのタップで白がコントロールを得た＝新しい攻撃の始まり。24秒にセットしてスタートする。',
        },
        scorer: {
          kind: 'apArrow',
          to: 'B',
          explanation:
            '最初のコントロールが決まったら、APアローはコントロールを得たチーム（白）の「相手」＝赤方向にセットする。次のヘルドボールは赤ボールになる。',
        },
      },
      refs: ['knowledge/08-to-scoresheet', 'knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-002',
      quarter: 1,
      gameClockMs: 339000,
      type: 'fieldGoal',
      narration: '白7番、ドライブからレイアップ成功！白に2点',
      team: 'A',
      playerNo: 7,
      points: 2,
      shot: 24,
      expect: {
        'sc-operator': {
          action: 'reset24',
          explanation:
            'ボールが正当にバスケットに入ったら24秒にリセット。相手チーム（赤）の新しい攻撃が始まる。',
        },
        scorer: {
          kind: 'mark',
          mark: {
            cell: { kind: 'score', team: 'A', score: 2 },
            mark: { symbol: 'fg', playerNo: 7 },
            color: 'red',
          },
          explanation:
            'FG（2点）は白の累計2点目のマスに斜線（／）、番号欄に得点者の7。第1Qは赤ペンで書く。',
        },
      },
      refs: ['knowledge/08-to-scoresheet', 'knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-003',
      quarter: 1,
      gameClockMs: 317000,
      type: 'fieldGoal',
      narration: '赤5番がミドルシュートを沈める！赤に2点',
      team: 'B',
      playerNo: 5,
      points: 2,
      shot: 24,
      expect: {
        'sc-operator': {
          action: 'reset24',
          explanation: 'ゴール成功で攻守交代。白の新しい攻撃が始まるので24秒にリセット。',
        },
        scorer: {
          kind: 'mark',
          mark: {
            cell: { kind: 'score', team: 'B', score: 2 },
            mark: { symbol: 'fg', playerNo: 5 },
            color: 'red',
          },
          explanation: '赤の累計2点目のマスに／、番号欄に5。第1Qは赤ペン。',
        },
      },
      refs: ['knowledge/08-to-scoresheet', 'knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-004',
      quarter: 1,
      gameClockMs: 296000,
      type: 'steal',
      narration: '白のパスを赤4番がスティール！そのまま前へ持ち込む',
      team: 'B',
      playerNo: 4,
      shot: 24,
      expect: {
        'sc-operator': {
          action: 'reset24',
          explanation:
            'スティールで新たなチーム（赤）がコントロールを得た瞬間に24秒へ即リセット。プレーは止まらないのでクロックはそのまま流す。',
        },
      },
      refs: ['knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-005',
      quarter: 1,
      gameClockMs: 290000,
      type: 'fieldGoal',
      narration: '速攻から赤9番がレイアップ成功！赤に2点',
      team: 'B',
      playerNo: 9,
      points: 2,
      shot: 24,
      expect: {
        'sc-operator': {
          action: 'reset24',
          explanation: 'ゴール成功。白の新しい攻撃が始まるので24秒にリセット。',
        },
        scorer: {
          kind: 'mark',
          mark: {
            cell: { kind: 'score', team: 'B', score: 4 },
            mark: { symbol: 'fg', playerNo: 9 },
            color: 'red',
          },
          explanation: '赤の累計4点目のマスに／、番号欄に9。第1Qは赤ペン。',
        },
      },
      refs: ['knowledge/08-to-scoresheet', 'knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-006',
      quarter: 1,
      gameClockMs: 282000,
      type: 'outOfBounds',
      narration: '白のパスを赤6番がタップしてボールはアウトオブバウンズ。白ボールのスローイン',
      team: 'A',
      shot: 'none',
      expect: {
        'sc-operator': {
          action: 'keep',
          explanation:
            'ボールを外に出したのは赤で、引き続き白ボールのスローイン。コントロールが変わらないのでSCは触らず継続。',
        },
      },
      refs: ['knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-007',
      quarter: 1,
      gameClockMs: 282000,
      type: 'throwIn',
      narration: '白のスローインでリスタート',
      team: 'A',
      shot: 'none',
      expect: {},
      refs: ['knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-008',
      quarter: 1,
      gameClockMs: 274000,
      type: 'foul',
      narration: 'シュートに行った白5番に赤4番がファウル！フリースロー2本',
      team: 'B',
      playerNo: 4,
      shot: 'hide',
      expect: {
        'sc-operator': {
          action: 'reset24',
          explanation:
            'フリースローが与えられるファウル。24秒にリセットした上で、FT中は表示を消しておく（消せない機材は24のまま）。',
        },
        scorer: {
          kind: 'mark',
          mark: {
            cell: { kind: 'foul', team: 'B', row: '4', slot: 1 },
            mark: { symbol: 'P', subscript: 2 },
            color: 'red',
          },
          explanation:
            'ファウルした赤4番の行の左から1つ目の枠にP。FT2本つきなので右下に添え字の2。第1Qは赤ペン。',
        },
      },
      refs: ['knowledge/08-to-scoresheet', 'knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-009',
      quarter: 1,
      gameClockMs: 274000,
      type: 'freeThrow',
      narration: '白5番のフリースロー1本目……成功！白に1点',
      team: 'A',
      playerNo: 5,
      points: 1,
      shot: 'none',
      expect: {
        scorer: {
          kind: 'mark',
          mark: {
            cell: { kind: 'score', team: 'A', score: 3 },
            mark: { symbol: 'ft', playerNo: 5 },
            color: 'red',
          },
          explanation: 'FT成功は1点。白の累計3点目のマスを●で塗りつぶし、番号欄に5。赤ペン。',
        },
      },
      refs: ['knowledge/08-to-scoresheet'],
    },
    {
      id: 'ev-010',
      quarter: 1,
      gameClockMs: 274000,
      type: 'freeThrow',
      narration: 'フリースロー2本目も成功！白に1点。次は赤ボール',
      team: 'A',
      playerNo: 5,
      points: 1,
      shot: 24,
      expect: {
        'sc-operator': {
          action: 'reset24',
          explanation:
            '最後のFTが成功したら赤のエンドラインスローイン＝新しい攻撃。24秒にセットする（スローインのタッチでスタート）。',
        },
        scorer: {
          kind: 'mark',
          mark: {
            cell: { kind: 'score', team: 'A', score: 4 },
            mark: { symbol: 'ft', playerNo: 5 },
            color: 'red',
          },
          explanation: '2本目も成功。白の累計4点目のマスを●で塗りつぶす。赤ペン。',
        },
      },
      refs: ['knowledge/08-to-scoresheet', 'knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-011',
      quarter: 1,
      gameClockMs: 274000,
      type: 'throwIn',
      narration: '赤のエンドラインスローインでリスタート',
      team: 'B',
      shot: 'none',
      expect: {},
      refs: ['knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-012',
      quarter: 1,
      gameClockMs: 253000,
      type: 'rebound',
      narration: '赤11番のシュートはリングに当たって外れる……赤9番がオフェンスリバウンド！',
      team: 'B',
      playerNo: 9,
      shot: 14,
      expect: {
        'sc-operator': {
          action: 'reset14',
          explanation:
            'ショットがリングに触れ、攻撃していた赤側が再びコントロール。U12でも14秒にリセットする数少ないケース。',
        },
      },
      refs: ['knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-013',
      quarter: 1,
      gameClockMs: 246000,
      type: 'fieldGoal',
      narration: '赤9番がそのままねじ込んだ！赤に2点',
      team: 'B',
      playerNo: 9,
      points: 2,
      shot: 24,
      expect: {
        'sc-operator': {
          action: 'reset24',
          explanation: 'ゴール成功。白の新しい攻撃が始まるので24秒にリセット。',
        },
        scorer: {
          kind: 'mark',
          mark: {
            cell: { kind: 'score', team: 'B', score: 6 },
            mark: { symbol: 'fg', playerNo: 9 },
            color: 'red',
          },
          explanation: '赤の累計6点目のマスに／、番号欄に9。赤ペン。',
        },
      },
      refs: ['knowledge/08-to-scoresheet', 'knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-014',
      quarter: 1,
      gameClockMs: 224000,
      type: 'violation',
      narration: '白7番、トラベリングの笛！赤ボールに',
      team: 'A',
      playerNo: 7,
      shot: 24,
      expect: {
        'sc-operator': {
          action: 'reset24',
          explanation:
            'トラベリングで攻守交代。新しいチーム（赤）のスローインになるので24秒にリセット（U12は常に24）。',
        },
      },
      refs: ['knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-015',
      quarter: 1,
      gameClockMs: 224000,
      type: 'substitution',
      narration: '白チームが交代。4番に代わって10番がコートへ',
      team: 'A',
      playerNo: 10,
      shot: 'none',
      expect: {},
      refs: ['knowledge/07-to-basics'],
    },
    {
      id: 'ev-016',
      quarter: 1,
      gameClockMs: 224000,
      type: 'throwIn',
      narration: '赤のスローインでリスタート',
      team: 'B',
      shot: 'none',
      expect: {},
      refs: ['knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-017',
      quarter: 1,
      gameClockMs: 202000,
      type: 'fieldGoal',
      narration: '赤5番、カットインから決めた！赤に2点',
      team: 'B',
      playerNo: 5,
      points: 2,
      shot: 24,
      expect: {
        'sc-operator': {
          action: 'reset24',
          explanation: 'ゴール成功。白の新しい攻撃が始まるので24秒にリセット。',
        },
        scorer: {
          kind: 'mark',
          mark: {
            cell: { kind: 'score', team: 'B', score: 8 },
            mark: { symbol: 'fg', playerNo: 5 },
            color: 'red',
          },
          explanation: '赤の累計8点目のマスに／、番号欄に5。赤ペン。',
        },
      },
      refs: ['knowledge/08-to-scoresheet', 'knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-018',
      quarter: 1,
      gameClockMs: 198000,
      type: 'timeout',
      narration: '白チームがタイムアウトを請求。認められました',
      team: 'A',
      shot: 'none',
      expect: {
        scorer: {
          kind: 'mark',
          mark: {
            cell: { kind: 'timeout', team: 'A', row: '第1Q', slot: 1 },
            mark: { symbol: 'timeout', value: 3 },
            color: 'red',
          },
          explanation:
            'タイムアウト枠にはそのQの経過時間（分・切り上げ）を書く。6分Qで残り3:18＝経過2分42秒 → 切り上げて「3」。赤ペン。',
        },
      },
      refs: ['knowledge/08-to-scoresheet'],
    },
    {
      id: 'ev-019',
      quarter: 1,
      gameClockMs: 198000,
      type: 'throwIn',
      narration: 'タイムアウト明け、白のスローインでリスタート',
      team: 'A',
      shot: 24,
      expect: {},
      refs: ['knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-020',
      quarter: 1,
      gameClockMs: 177000,
      type: 'fieldGoal',
      narration: '白10番、ゴール下で決めた！白に2点',
      team: 'A',
      playerNo: 10,
      points: 2,
      shot: 24,
      expect: {
        'sc-operator': {
          action: 'reset24',
          explanation: 'ゴール成功。赤の新しい攻撃が始まるので24秒にリセット。',
        },
        scorer: {
          kind: 'mark',
          mark: {
            cell: { kind: 'score', team: 'A', score: 6 },
            mark: { symbol: 'fg', playerNo: 10 },
            color: 'red',
          },
          explanation: '白の累計6点目のマスに／、番号欄に10。赤ペン。',
        },
      },
      refs: ['knowledge/08-to-scoresheet', 'knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-021',
      quarter: 1,
      gameClockMs: 167000,
      type: 'jumpBallSituation',
      narration:
        '赤の攻撃中、ボールを持つ赤9番に白5番が絡んでヘルドボール！矢印は赤方向、赤ボールのスローインへ',
      shot: 'none',
      expect: {
        'sc-operator': {
          action: 'keep',
          explanation:
            'APアローで赤ボールになるが、赤はもともとコントロールしていたチーム。同じチームが続けるのでSCは継続。',
        },
        scorer: {
          kind: 'apArrow',
          to: 'A',
          explanation:
            '矢印が赤方向だったので赤ボールのスローイン。スローインが行われたらすぐに矢印を白方向へ反転させる。',
        },
      },
      refs: ['knowledge/08-to-scoresheet', 'knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-022',
      quarter: 1,
      gameClockMs: 167000,
      type: 'throwIn',
      narration: '赤のスローインでリスタート',
      team: 'B',
      shot: 'none',
      expect: {},
      refs: ['knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-023',
      quarter: 1,
      gameClockMs: 155000,
      type: 'fieldGoal',
      narration: '赤11番がジャンプシュート成功！赤に2点',
      team: 'B',
      playerNo: 11,
      points: 2,
      shot: 24,
      expect: {
        'sc-operator': {
          action: 'reset24',
          explanation: 'ゴール成功。白の新しい攻撃が始まるので24秒にリセット。',
        },
        scorer: {
          kind: 'mark',
          mark: {
            cell: { kind: 'score', team: 'B', score: 10 },
            mark: { symbol: 'fg', playerNo: 11 },
            color: 'red',
          },
          explanation: '赤の累計10点目のマスに／、番号欄に11。赤ペン。',
        },
      },
      refs: ['knowledge/08-to-scoresheet', 'knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-024',
      quarter: 1,
      gameClockMs: 133000,
      type: 'foul',
      narration: 'ドリブルする白7番に赤6番が手を出してファウル。白ボールのスローイン（FTなし）',
      team: 'B',
      playerNo: 6,
      shot: 24,
      expect: {
        'sc-operator': {
          action: 'reset24',
          explanation:
            'ディフェンスのファウルで白ボールのスローイン。U12にはフロントコートの概念がないので常に24秒にリセット。',
        },
        scorer: {
          kind: 'mark',
          mark: {
            cell: { kind: 'foul', team: 'B', row: '6', slot: 1 },
            mark: { symbol: 'P' },
            color: 'red',
          },
          explanation: '赤6番の行の1つ目の枠にP。FTなしなので添え字はつけない。赤ペン。',
        },
      },
      refs: ['knowledge/08-to-scoresheet', 'knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-025',
      quarter: 1,
      gameClockMs: 133000,
      type: 'throwIn',
      narration: '白のスローインでリスタート',
      team: 'A',
      shot: 'none',
      expect: {},
      refs: ['knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-026',
      quarter: 1,
      gameClockMs: 110000,
      type: 'fieldGoal',
      narration: '白5番、ショットクロックぎりぎりでジャンプシュート成功！白に2点',
      team: 'A',
      playerNo: 5,
      points: 2,
      shot: 24,
      expect: {
        'sc-operator': {
          action: 'reset24',
          explanation: 'ゴール成功。赤の新しい攻撃が始まるので24秒にリセット。',
        },
        scorer: {
          kind: 'mark',
          mark: {
            cell: { kind: 'score', team: 'A', score: 8 },
            mark: { symbol: 'fg', playerNo: 5 },
            color: 'red',
          },
          explanation: '白の累計8点目のマスに／、番号欄に5。赤ペン。',
        },
      },
      refs: ['knowledge/08-to-scoresheet', 'knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-027',
      quarter: 1,
      gameClockMs: 87000,
      type: 'violation',
      narration: '赤11番、ダブルドリブルの笛！白ボールに',
      team: 'B',
      playerNo: 11,
      shot: 24,
      expect: {
        'sc-operator': {
          action: 'reset24',
          explanation: 'ダブルドリブルで攻守交代。白の新しい攻撃なので24秒にリセット。',
        },
      },
      refs: ['knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-028',
      quarter: 1,
      gameClockMs: 87000,
      type: 'throwIn',
      narration: '白のスローインでリスタート',
      team: 'A',
      shot: 'none',
      expect: {},
      refs: ['knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-029',
      quarter: 1,
      gameClockMs: 64000,
      type: 'fieldGoal',
      narration: '白7番が今日3本目のシュートを決めた！白に2点',
      team: 'A',
      playerNo: 7,
      points: 2,
      shot: 24,
      expect: {
        'sc-operator': {
          action: 'reset24',
          explanation: 'ゴール成功。赤の新しい攻撃が始まるので24秒にリセット。',
        },
        scorer: {
          kind: 'mark',
          mark: {
            cell: { kind: 'score', team: 'A', score: 10 },
            mark: { symbol: 'fg', playerNo: 7 },
            color: 'red',
          },
          explanation: '白の累計10点目のマスに／、番号欄に7。赤ペン。',
        },
      },
      refs: ['knowledge/08-to-scoresheet', 'knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-030',
      quarter: 1,
      gameClockMs: 42000,
      type: 'fieldGoal',
      narration: '赤4番がドライブで切り込んで決めた！赤に2点',
      team: 'B',
      playerNo: 4,
      points: 2,
      shot: 24,
      expect: {
        'sc-operator': {
          action: 'reset24',
          explanation: 'ゴール成功。白の新しい攻撃が始まるので24秒にリセット。',
        },
        scorer: {
          kind: 'mark',
          mark: {
            cell: { kind: 'score', team: 'B', score: 12 },
            mark: { symbol: 'fg', playerNo: 4 },
            color: 'red',
          },
          explanation: '赤の累計12点目のマスに／、番号欄に4。赤ペン。',
        },
      },
      refs: ['knowledge/08-to-scoresheet', 'knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-031',
      quarter: 1,
      gameClockMs: 19000,
      type: 'fieldGoal',
      narration: '白10番、コーナーから決めた！白に2点',
      team: 'A',
      playerNo: 10,
      points: 2,
      shot: 24,
      expect: {
        'sc-operator': {
          action: 'reset24',
          explanation: 'ゴール成功。赤の新しい攻撃が始まるので24秒にリセット。',
        },
        scorer: {
          kind: 'mark',
          mark: {
            cell: { kind: 'score', team: 'A', score: 12 },
            mark: { symbol: 'fg', playerNo: 10 },
            color: 'red',
          },
          explanation: '白の累計12点目のマスに／、番号欄に10。赤ペン。',
        },
      },
      refs: ['knowledge/08-to-scoresheet', 'knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-032',
      quarter: 1,
      gameClockMs: 0,
      type: 'periodEnd',
      narration: 'ブザーが鳴って第1Q終了！12対12の同点',
      shot: 'hide',
      expect: {
        scorer: {
          kind: 'mark',
          mark: {
            cell: { kind: 'score', team: 'A', score: 12 },
            mark: { symbol: 'closeQ' },
            color: 'red',
          },
          explanation:
            'Q終了はそのQのペン（第1Q=赤）で、最後の得点（白の12点目）を太い○で囲み、すぐ下に太い横線を1本引く。',
        },
      },
      refs: ['knowledge/08-to-scoresheet'],
    },
    // ================= 第2Q（濃色ペン）: ペン持ち替え・▲・T・U・赤のTO =================
    {
      id: 'ev-033',
      quarter: 2,
      gameClockMs: 360000,
      type: 'periodStart',
      narration:
        'インターバル終了、第2Q開始！APアローは白方向、白ボールのスローインでスタート',
      team: 'A',
      shot: 24,
      expect: {
        'sc-operator': {
          action: 'reset24',
          explanation: 'Qの始まりはAPアローのスローインから。白の新しい攻撃なので24秒にセット。',
        },
        scorer: {
          kind: 'apArrow',
          to: 'B',
          explanation:
            'Q開始のAPスローインも「使ったらすぐ反転」。白がもらったので矢印を赤方向へ。',
        },
      },
      refs: ['knowledge/08-to-scoresheet', 'knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-034',
      quarter: 2,
      gameClockMs: 339000,
      type: 'fieldGoal',
      narration: '白5番、ミドルシュート成功！白に2点',
      team: 'A',
      playerNo: 5,
      points: 2,
      shot: 24,
      expect: {
        'sc-operator': {
          action: 'reset24',
          explanation: 'ゴール成功。赤の新しい攻撃が始まるので24秒にリセット。',
        },
        scorer: {
          kind: 'mark',
          mark: {
            cell: { kind: 'score', team: 'A', score: 14 },
            mark: { symbol: 'fg', playerNo: 5 },
            color: 'dark',
          },
          explanation:
            '第2Q・第4Qは濃色ペンに持ち替えて記入する。白の累計14点目に／、番号欄に5。',
        },
      },
      refs: ['knowledge/08-to-scoresheet', 'knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-035',
      quarter: 2,
      gameClockMs: 320000,
      type: 'fieldGoal',
      narration:
        '赤5番のシュートは外れる……こぼれ球を白6番がクリアしようとして自分のバスケットに入れてしまった！赤に2点',
      team: 'B',
      points: 2,
      shot: 24,
      expect: {
        'sc-operator': {
          action: 'reset24',
          explanation: 'ボールがバスケットに入ったので得点。白の新しい攻撃が始まり24秒にリセット。',
        },
        scorer: {
          kind: 'mark',
          mark: {
            cell: { kind: 'score', team: 'B', score: 14 },
            mark: { symbol: 'ownGoal' },
            color: 'dark',
          },
          explanation:
            'U12のオウンゴールは相手チーム（赤）の得点として記入し、番号欄には背番号の代わりに▲を書く。濃色ペン。',
        },
      },
      refs: ['knowledge/08-to-scoresheet', 'knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-036',
      quarter: 2,
      gameClockMs: 320000,
      type: 'foul',
      narration: 'いまの判定に赤9番が激しく抗議。テクニカルファウル！白にフリースロー1本',
      team: 'B',
      playerNo: 9,
      shot: 'hide',
      expect: {
        scorer: {
          kind: 'mark',
          mark: {
            cell: { kind: 'foul', team: 'B', row: '9', slot: 1 },
            mark: { symbol: 'T', subscript: 1 },
            color: 'dark',
          },
          explanation:
            'プレーヤーのテクニカルファウルはT。罰則はFT1本なので右下に添え字の1。濃色ペン。',
        },
      },
      refs: ['knowledge/08-to-scoresheet'],
    },
    {
      id: 'ev-037',
      quarter: 2,
      gameClockMs: 320000,
      type: 'freeThrow',
      narration: 'テクニカルの罰則フリースロー、白7番が決めた！白に1点',
      team: 'A',
      playerNo: 7,
      points: 1,
      shot: 'none',
      expect: {
        scorer: {
          kind: 'mark',
          mark: {
            cell: { kind: 'score', team: 'A', score: 15 },
            mark: { symbol: 'ft', playerNo: 7 },
            color: 'dark',
          },
          explanation: 'FT成功は1点。白の累計15点目を●で塗りつぶし、番号欄に7。濃色ペン。',
        },
      },
      refs: ['knowledge/08-to-scoresheet'],
    },
    {
      id: 'ev-038',
      quarter: 2,
      gameClockMs: 320000,
      type: 'throwIn',
      narration: 'テクニカルの処理が終わり、中断時点から白ボールのスローインで再開',
      team: 'A',
      shot: 24,
      expect: {},
      refs: ['knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-039',
      quarter: 2,
      gameClockMs: 299000,
      type: 'fieldGoal',
      narration: '白10番、ドライブから決めた！白に2点',
      team: 'A',
      playerNo: 10,
      points: 2,
      shot: 24,
      expect: {
        'sc-operator': {
          action: 'reset24',
          explanation: 'ゴール成功。赤の新しい攻撃が始まるので24秒にリセット。',
        },
        scorer: {
          kind: 'mark',
          mark: {
            cell: { kind: 'score', team: 'A', score: 17 },
            mark: { symbol: 'fg', playerNo: 10 },
            color: 'dark',
          },
          explanation: '白の累計17点目に／、番号欄に10。濃色ペン。',
        },
      },
      refs: ['knowledge/08-to-scoresheet', 'knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-040',
      quarter: 2,
      gameClockMs: 291000,
      type: 'foul',
      narration:
        '速攻に走る赤4番を白8番が後ろから抱えて止めた！アンスポーツマンライクファウル、赤にFT2本＋ボール',
      team: 'A',
      playerNo: 8,
      shot: 'hide',
      expect: {
        'sc-operator': {
          action: 'reset24',
          explanation: 'FTが与えられるファウル。24秒にリセットしてFT中は表示を消す。',
        },
        scorer: {
          kind: 'mark',
          mark: {
            cell: { kind: 'foul', team: 'A', row: '8', slot: 1 },
            mark: { symbol: 'U', subscript: 2 },
            color: 'dark',
          },
          explanation:
            'アンスポーツマンライクファウルはU。FT2本なので添え字の2。白8番の行の1つ目の枠に濃色ペンで。',
        },
      },
      refs: ['knowledge/08-to-scoresheet', 'knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-041',
      quarter: 2,
      gameClockMs: 291000,
      type: 'freeThrow',
      narration: '赤4番のフリースロー1本目成功！赤に1点',
      team: 'B',
      playerNo: 4,
      points: 1,
      shot: 'none',
      expect: {
        scorer: {
          kind: 'mark',
          mark: {
            cell: { kind: 'score', team: 'B', score: 15 },
            mark: { symbol: 'ft', playerNo: 4 },
            color: 'dark',
          },
          explanation: 'FT成功は1点。赤の累計15点目を●で塗りつぶし、番号欄に4。濃色ペン。',
        },
      },
      refs: ['knowledge/08-to-scoresheet'],
    },
    {
      id: 'ev-042',
      quarter: 2,
      gameClockMs: 291000,
      type: 'freeThrow',
      narration: '2本目も成功！アンスポの罰則により、続けて赤ボールのスローイン',
      team: 'B',
      playerNo: 4,
      points: 1,
      shot: 24,
      expect: {
        'sc-operator': {
          action: 'reset24',
          explanation:
            'アンスポの罰則はFT2本＋ボール。FTのあと赤のスローインで新しい攻撃が始まるので24秒。',
        },
        scorer: {
          kind: 'mark',
          mark: {
            cell: { kind: 'score', team: 'B', score: 16 },
            mark: { symbol: 'ft', playerNo: 4 },
            color: 'dark',
          },
          explanation: '2本目も成功。赤の累計16点目を●で塗りつぶす。濃色ペン。',
        },
      },
      refs: ['knowledge/08-to-scoresheet', 'knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-043',
      quarter: 2,
      gameClockMs: 291000,
      type: 'throwIn',
      narration: '赤のスローインでリスタート',
      team: 'B',
      shot: 'none',
      expect: {},
      refs: ['knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-044',
      quarter: 2,
      gameClockMs: 270000,
      type: 'fieldGoal',
      narration: '赤11番がコーナーから決めた！赤に2点',
      team: 'B',
      playerNo: 11,
      points: 2,
      shot: 24,
      expect: {
        'sc-operator': {
          action: 'reset24',
          explanation: 'ゴール成功。白の新しい攻撃が始まるので24秒にリセット。',
        },
        scorer: {
          kind: 'mark',
          mark: {
            cell: { kind: 'score', team: 'B', score: 18 },
            mark: { symbol: 'fg', playerNo: 11 },
            color: 'dark',
          },
          explanation: '赤の累計18点目に／、番号欄に11。濃色ペン。',
        },
      },
      refs: ['knowledge/08-to-scoresheet', 'knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-045',
      quarter: 2,
      gameClockMs: 150000,
      type: 'play',
      narration: '両チーム一進一退の攻防が続く……白が攻め込んだところで——',
      shot: 24,
      expect: {},
      refs: ['knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-046',
      quarter: 2,
      gameClockMs: 128000,
      type: 'violation',
      narration: '白8番、トラベリングの笛！赤ボールに',
      team: 'A',
      playerNo: 8,
      shot: 24,
      expect: {
        'sc-operator': {
          action: 'reset24',
          explanation: 'トラベリングで攻守交代。赤の新しい攻撃なので24秒にリセット。',
        },
      },
      refs: ['knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-047',
      quarter: 2,
      gameClockMs: 128000,
      type: 'timeout',
      narration: 'ここで赤チームがタイムアウトを請求。認められました',
      team: 'B',
      shot: 'none',
      expect: {
        scorer: {
          kind: 'mark',
          mark: {
            cell: { kind: 'timeout', team: 'B', row: '第2Q', slot: 1 },
            mark: { symbol: 'timeout', value: 4 },
            color: 'dark',
          },
          explanation:
            '赤の第2Q枠に経過分。残り2:08＝経過3分52秒 → 切り上げて「4」。濃色ペンで。',
        },
      },
      refs: ['knowledge/08-to-scoresheet'],
    },
    {
      id: 'ev-048',
      quarter: 2,
      gameClockMs: 128000,
      type: 'throwIn',
      narration: 'タイムアウト明け、赤のスローインでリスタート',
      team: 'B',
      shot: 'none',
      expect: {},
      refs: ['knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-049',
      quarter: 2,
      gameClockMs: 106000,
      type: 'fieldGoal',
      narration: '赤9番がゴール下で押し込んだ！赤に2点',
      team: 'B',
      playerNo: 9,
      points: 2,
      shot: 24,
      expect: {
        'sc-operator': {
          action: 'reset24',
          explanation: 'ゴール成功。白の新しい攻撃が始まるので24秒にリセット。',
        },
        scorer: {
          kind: 'mark',
          mark: {
            cell: { kind: 'score', team: 'B', score: 20 },
            mark: { symbol: 'fg', playerNo: 9 },
            color: 'dark',
          },
          explanation: '赤の累計20点目に／、番号欄に9。濃色ペン。',
        },
      },
      refs: ['knowledge/08-to-scoresheet', 'knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-050',
      quarter: 2,
      gameClockMs: 30000,
      type: 'play',
      narration: '前半終了間際、白がじっくり攻める——',
      shot: 24,
      expect: {},
      refs: ['knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-051',
      quarter: 2,
      gameClockMs: 8000,
      type: 'fieldGoal',
      narration: '白7番がプルアップジャンパー！白に2点',
      team: 'A',
      playerNo: 7,
      points: 2,
      shot: 24,
      expect: {
        'sc-operator': {
          action: 'reset24',
          explanation: 'ゴール成功。赤の新しい攻撃が始まるので24秒にリセット。',
        },
        scorer: {
          kind: 'mark',
          mark: {
            cell: { kind: 'score', team: 'A', score: 19 },
            mark: { symbol: 'fg', playerNo: 7 },
            color: 'dark',
          },
          explanation: '白の累計19点目に／、番号欄に7。濃色ペン。',
        },
      },
      refs: ['knowledge/08-to-scoresheet', 'knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-052',
      quarter: 2,
      gameClockMs: 0,
      type: 'periodEnd',
      narration: '前半終了のブザー！19対20で赤リード',
      shot: 'hide',
      expect: {
        scorer: {
          kind: 'mark',
          mark: {
            cell: { kind: 'score', team: 'A', score: 19 },
            mark: { symbol: 'closeQ' },
            color: 'dark',
          },
          explanation:
            '第2Qの締めは濃色ペン。最後の得点（白の19点目）を太い○で囲み、下に太い横線1本。',
        },
      },
      refs: ['knowledge/08-to-scoresheet'],
    },
    // ================= 第3Q（赤ペンに戻す）: M・C・同一選手の2個目 =================
    {
      id: 'ev-053',
      quarter: 3,
      gameClockMs: 360000,
      type: 'periodStart',
      narration: '後半・第3Q開始！APアローは赤方向、赤ボールのスローインでスタート',
      team: 'B',
      shot: 24,
      expect: {
        'sc-operator': {
          action: 'reset24',
          explanation: 'Q開始のAPスローインで赤の新しい攻撃が始まる。24秒にセット。',
        },
        scorer: {
          kind: 'apArrow',
          to: 'A',
          explanation: '矢印は赤方向だったので赤ボールでスタート。使ったらすぐ白方向へ反転。',
        },
      },
      refs: ['knowledge/08-to-scoresheet', 'knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-054',
      quarter: 3,
      gameClockMs: 338000,
      type: 'fieldGoal',
      narration: '赤5番、後半最初のシュートを沈める！赤に2点',
      team: 'B',
      playerNo: 5,
      points: 2,
      shot: 24,
      expect: {
        'sc-operator': {
          action: 'reset24',
          explanation: 'ゴール成功。白の新しい攻撃が始まるので24秒にリセット。',
        },
        scorer: {
          kind: 'mark',
          mark: {
            cell: { kind: 'score', team: 'B', score: 22 },
            mark: { symbol: 'fg', playerNo: 5 },
            color: 'red',
          },
          explanation:
            '第3Qは赤ペンに戻して記入する。赤の累計22点目に／、番号欄に5。',
        },
      },
      refs: ['knowledge/08-to-scoresheet', 'knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-055',
      quarter: 3,
      gameClockMs: 330000,
      type: 'foul',
      narration:
        '赤の攻撃中、守る白チームがゾーン気味と判定！マンツーマンペナルティが宣せられた。引き続き赤ボールのスローイン',
      team: 'A',
      shot: 'none',
      expect: {
        'sc-operator': {
          action: 'keep',
          explanation:
            '笛でプレーは止まるが、ボールは引き続き赤。コントロールが変わらないのでSCは継続。',
        },
        scorer: {
          kind: 'mark',
          mark: {
            cell: { kind: 'foul', team: 'A', row: 'HC', slot: 1 },
            mark: { symbol: 'M' },
            color: 'red',
          },
          explanation:
            'マンツーマンペナルティ（U12・U15のみ）はHCの欄にM。チームファウルには数えない。M3個でGD。第3Qは赤ペン。',
        },
      },
      refs: ['knowledge/08-to-scoresheet', 'knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-056',
      quarter: 3,
      gameClockMs: 330000,
      type: 'throwIn',
      narration: '赤のスローインでリスタート',
      team: 'B',
      shot: 'none',
      expect: {},
      refs: ['knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-057',
      quarter: 3,
      gameClockMs: 316000,
      type: 'fieldGoal',
      narration: '赤9番がミドルシュート成功！赤に2点',
      team: 'B',
      playerNo: 9,
      points: 2,
      shot: 24,
      expect: {
        'sc-operator': {
          action: 'reset24',
          explanation: 'ゴール成功。白の新しい攻撃が始まるので24秒にリセット。',
        },
        scorer: {
          kind: 'mark',
          mark: {
            cell: { kind: 'score', team: 'B', score: 24 },
            mark: { symbol: 'fg', playerNo: 9 },
            color: 'red',
          },
          explanation: '赤の累計24点目に／、番号欄に9。赤ペン。',
        },
      },
      refs: ['knowledge/08-to-scoresheet', 'knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-058',
      quarter: 3,
      gameClockMs: 294000,
      type: 'foul',
      narration: 'ドリブルで抜こうとした白7番を赤4番が腕で止めた。ファウル！白ボールのスローイン',
      team: 'B',
      playerNo: 4,
      shot: 24,
      expect: {
        'sc-operator': {
          action: 'reset24',
          explanation: 'ディフェンスのファウルで白ボールのスローイン。U12は常に24秒にリセット。',
        },
        scorer: {
          kind: 'mark',
          mark: {
            cell: { kind: 'foul', team: 'B', row: '4', slot: 2 },
            mark: { symbol: 'P' },
            color: 'red',
          },
          explanation:
            '赤4番は第1Qに続いて2個目のファウル。同じ行の左から2つ目の枠にP。FTなしなので添え字なし。赤ペン。',
        },
      },
      refs: ['knowledge/08-to-scoresheet', 'knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-059',
      quarter: 3,
      gameClockMs: 294000,
      type: 'throwIn',
      narration: '白のスローインでリスタート',
      team: 'A',
      shot: 'none',
      expect: {},
      refs: ['knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-060',
      quarter: 3,
      gameClockMs: 272000,
      type: 'fieldGoal',
      narration: '白10番、リバースレイアップ成功！白に2点',
      team: 'A',
      playerNo: 10,
      points: 2,
      shot: 24,
      expect: {
        'sc-operator': {
          action: 'reset24',
          explanation: 'ゴール成功。赤の新しい攻撃が始まるので24秒にリセット。',
        },
        scorer: {
          kind: 'mark',
          mark: {
            cell: { kind: 'score', team: 'A', score: 21 },
            mark: { symbol: 'fg', playerNo: 10 },
            color: 'red',
          },
          explanation: '白の累計21点目に／、番号欄に10。赤ペン。',
        },
      },
      refs: ['knowledge/08-to-scoresheet', 'knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-061',
      quarter: 3,
      gameClockMs: 251000,
      type: 'rebound',
      narration: '赤11番のシュートはリングに弾かれる……赤9番がオフェンスリバウンド！',
      team: 'B',
      playerNo: 9,
      shot: 14,
      expect: {
        'sc-operator': {
          action: 'reset14',
          explanation:
            'リングに触れたあと攻撃側（赤）が再びコントロール。U12でも14秒にリセットするケース。',
        },
      },
      refs: ['knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-062',
      quarter: 3,
      gameClockMs: 245000,
      type: 'fieldGoal',
      narration: '赤9番がセカンドチャンスをものにした！赤に2点',
      team: 'B',
      playerNo: 9,
      points: 2,
      shot: 24,
      expect: {
        'sc-operator': {
          action: 'reset24',
          explanation: 'ゴール成功。白の新しい攻撃が始まるので24秒にリセット。',
        },
        scorer: {
          kind: 'mark',
          mark: {
            cell: { kind: 'score', team: 'B', score: 26 },
            mark: { symbol: 'fg', playerNo: 9 },
            color: 'red',
          },
          explanation: '赤の累計26点目に／、番号欄に9。赤ペン。',
        },
      },
      refs: ['knowledge/08-to-scoresheet', 'knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-063',
      quarter: 3,
      gameClockMs: 245000,
      type: 'foul',
      narration:
        'いまのリバウンド争いの判定に白のヘッドコーチが激しく抗議！HC自身にテクニカルファウル。赤にFT1本',
      team: 'A',
      shot: 'hide',
      expect: {
        scorer: {
          kind: 'mark',
          mark: {
            cell: { kind: 'foul', team: 'A', row: 'HC', slot: 2 },
            mark: { symbol: 'C', subscript: 1 },
            color: 'red',
          },
          explanation:
            'HC自身の言動によるテクニカルはC。FT1本なので添え字の1。HC欄はMに続く2つ目の枠。赤ペン。',
        },
      },
      refs: ['knowledge/08-to-scoresheet'],
    },
    {
      id: 'ev-064',
      quarter: 3,
      gameClockMs: 245000,
      type: 'freeThrow',
      narration: 'テクニカルの罰則フリースロー、赤5番が成功！赤に1点',
      team: 'B',
      playerNo: 5,
      points: 1,
      shot: 'none',
      expect: {
        scorer: {
          kind: 'mark',
          mark: {
            cell: { kind: 'score', team: 'B', score: 27 },
            mark: { symbol: 'ft', playerNo: 5 },
            color: 'red',
          },
          explanation: 'FT成功は1点。赤の累計27点目を●で塗りつぶし、番号欄に5。赤ペン。',
        },
      },
      refs: ['knowledge/08-to-scoresheet'],
    },
    {
      id: 'ev-065',
      quarter: 3,
      gameClockMs: 245000,
      type: 'throwIn',
      narration: 'テクニカルの処理後、中断時点＝赤のゴール後の白スローインから再開',
      team: 'A',
      shot: 24,
      expect: {},
      refs: ['knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-066',
      quarter: 3,
      gameClockMs: 224000,
      type: 'fieldGoal',
      narration: '白5番がスクリーンを使って決めた！白に2点',
      team: 'A',
      playerNo: 5,
      points: 2,
      shot: 24,
      expect: {
        'sc-operator': {
          action: 'reset24',
          explanation: 'ゴール成功。赤の新しい攻撃が始まるので24秒にリセット。',
        },
        scorer: {
          kind: 'mark',
          mark: {
            cell: { kind: 'score', team: 'A', score: 23 },
            mark: { symbol: 'fg', playerNo: 5 },
            color: 'red',
          },
          explanation: '白の累計23点目に／、番号欄に5。赤ペン。',
        },
      },
      refs: ['knowledge/08-to-scoresheet', 'knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-067',
      quarter: 3,
      gameClockMs: 100000,
      type: 'play',
      narration: '白が守備を立て直し、両チーム決め手のないまま時間が過ぎる——',
      shot: 24,
      expect: {},
      refs: ['knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-068',
      quarter: 3,
      gameClockMs: 85000,
      type: 'outOfBounds',
      narration: '赤のパスが白8番の足に当たってアウトオブバウンズ。赤ボールのまま',
      team: 'B',
      shot: 'none',
      expect: {
        'sc-operator': {
          action: 'keep',
          explanation:
            'ボールを外に出したのは白で、引き続き赤ボールのスローイン。コントロールが変わらないのでSCは継続。',
        },
      },
      refs: ['knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-069',
      quarter: 3,
      gameClockMs: 85000,
      type: 'throwIn',
      narration: '赤のスローインでリスタート',
      team: 'B',
      shot: 'none',
      expect: {},
      refs: ['knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-070',
      quarter: 3,
      gameClockMs: 78000,
      type: 'fieldGoal',
      narration: '赤4番、ベースラインを割って決めた！赤に2点',
      team: 'B',
      playerNo: 4,
      points: 2,
      shot: 24,
      expect: {
        'sc-operator': {
          action: 'reset24',
          explanation: 'ゴール成功。白の新しい攻撃が始まるので24秒にリセット。',
        },
        scorer: {
          kind: 'mark',
          mark: {
            cell: { kind: 'score', team: 'B', score: 29 },
            mark: { symbol: 'fg', playerNo: 4 },
            color: 'red',
          },
          explanation: '赤の累計29点目に／、番号欄に4。赤ペン。',
        },
      },
      refs: ['knowledge/08-to-scoresheet', 'knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-071',
      quarter: 3,
      gameClockMs: 56000,
      type: 'fieldGoal',
      narration: '白7番がすかさず返す！白に2点',
      team: 'A',
      playerNo: 7,
      points: 2,
      shot: 24,
      expect: {
        'sc-operator': {
          action: 'reset24',
          explanation: 'ゴール成功。赤の新しい攻撃が始まるので24秒にリセット。',
        },
        scorer: {
          kind: 'mark',
          mark: {
            cell: { kind: 'score', team: 'A', score: 25 },
            mark: { symbol: 'fg', playerNo: 7 },
            color: 'red',
          },
          explanation: '白の累計25点目に／、番号欄に7。赤ペン。',
        },
      },
      refs: ['knowledge/08-to-scoresheet', 'knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-072',
      quarter: 3,
      gameClockMs: 34000,
      type: 'violation',
      narration: '赤11番、ダブルドリブルの笛！白ボールに',
      team: 'B',
      playerNo: 11,
      shot: 24,
      expect: {
        'sc-operator': {
          action: 'reset24',
          explanation: 'ダブルドリブルで攻守交代。白の新しい攻撃なので24秒にリセット。',
        },
      },
      refs: ['knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-073',
      quarter: 3,
      gameClockMs: 34000,
      type: 'throwIn',
      narration: '白のスローインでリスタート',
      team: 'A',
      shot: 'none',
      expect: {},
      refs: ['knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-074',
      quarter: 3,
      gameClockMs: 12000,
      type: 'fieldGoal',
      narration: '白7番、第3Q終了間際に決めた！白に2点',
      team: 'A',
      playerNo: 7,
      points: 2,
      shot: 24,
      expect: {
        'sc-operator': {
          action: 'reset24',
          explanation: 'ゴール成功。赤の新しい攻撃が始まるので24秒にリセット。',
        },
        scorer: {
          kind: 'mark',
          mark: {
            cell: { kind: 'score', team: 'A', score: 27 },
            mark: { symbol: 'fg', playerNo: 7 },
            color: 'red',
          },
          explanation: '白の累計27点目に／、番号欄に7。赤ペン。',
        },
      },
      refs: ['knowledge/08-to-scoresheet', 'knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-075',
      quarter: 3,
      gameClockMs: 0,
      type: 'periodEnd',
      narration: '第3Q終了！27対29、赤が2点リードで最終Qへ',
      shot: 'hide',
      expect: {
        scorer: {
          kind: 'mark',
          mark: {
            cell: { kind: 'score', team: 'A', score: 27 },
            mark: { symbol: 'closeQ' },
            color: 'red',
          },
          explanation:
            '第3Qの締めは赤ペン。最後の得点（白の27点目）を太い○で囲み、下に太い横線1本。',
        },
      },
      refs: ['knowledge/08-to-scoresheet'],
    },
    // ================= 第4Q（濃色ペン）: B・SC violation・ヘルドボール継続・closeGame =================
    {
      id: 'ev-076',
      quarter: 4,
      gameClockMs: 360000,
      type: 'periodStart',
      narration: '最終第4Q！APアローは白方向、白ボールのスローインでスタート',
      team: 'A',
      shot: 24,
      expect: {
        'sc-operator': {
          action: 'reset24',
          explanation: 'Q開始のAPスローインで白の新しい攻撃が始まる。24秒にセット。',
        },
        scorer: {
          kind: 'apArrow',
          to: 'B',
          explanation: '白がAPスローインを使ったので、矢印をすぐ赤方向へ反転。',
        },
      },
      refs: ['knowledge/08-to-scoresheet', 'knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-077',
      quarter: 4,
      gameClockMs: 338000,
      type: 'fieldGoal',
      narration: '白7番、最終Q最初のアタックを決めた！白に2点',
      team: 'A',
      playerNo: 7,
      points: 2,
      shot: 24,
      expect: {
        'sc-operator': {
          action: 'reset24',
          explanation: 'ゴール成功。赤の新しい攻撃が始まるので24秒にリセット。',
        },
        scorer: {
          kind: 'mark',
          mark: {
            cell: { kind: 'score', team: 'A', score: 29 },
            mark: { symbol: 'fg', playerNo: 7 },
            color: 'dark',
          },
          explanation: '第4Qは濃色ペンに持ち替え。白の累計29点目に／、番号欄に7。',
        },
      },
      refs: ['knowledge/08-to-scoresheet', 'knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-078',
      quarter: 4,
      gameClockMs: 338000,
      type: 'foul',
      narration:
        '白ベンチの交代要員が大声で判定に抗議！ベンチテクニカル。HCにBが記録され、赤にFT1本',
      team: 'A',
      shot: 'hide',
      expect: {
        scorer: {
          kind: 'mark',
          mark: {
            cell: { kind: 'foul', team: 'A', row: 'HC', slot: 3 },
            mark: { symbol: 'B', subscript: 1 },
            color: 'dark',
          },
          explanation:
            'ベンチ（交代要員等）の言動によるテクニカルはHCの欄にB、FT1本で添え字の1。M・Cに続く3つ目の枠。濃色ペン。',
        },
      },
      refs: ['knowledge/08-to-scoresheet'],
    },
    {
      id: 'ev-079',
      quarter: 4,
      gameClockMs: 338000,
      type: 'freeThrow',
      narration: '罰則フリースロー、赤9番が沈めて赤に1点',
      team: 'B',
      playerNo: 9,
      points: 1,
      shot: 'none',
      expect: {
        scorer: {
          kind: 'mark',
          mark: {
            cell: { kind: 'score', team: 'B', score: 30 },
            mark: { symbol: 'ft', playerNo: 9 },
            color: 'dark',
          },
          explanation: 'FT成功は1点。赤の累計30点目を●で塗りつぶし、番号欄に9。濃色ペン。',
        },
      },
      refs: ['knowledge/08-to-scoresheet'],
    },
    {
      id: 'ev-080',
      quarter: 4,
      gameClockMs: 338000,
      type: 'throwIn',
      narration: '中断時点から再開。赤ボールのスローイン',
      team: 'B',
      shot: 24,
      expect: {},
      refs: ['knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-081',
      quarter: 4,
      gameClockMs: 314000,
      type: 'violation',
      narration: '赤、攻めあぐねて24秒オーバー！ショットクロックバイオレーションのブザーが鳴る',
      team: 'B',
      shot: 24,
      expect: {
        'sc-operator': {
          action: 'reset24',
          explanation:
            '24秒の経過はSCオペレーターのブザーで知らせる。バイオレーションで白ボールになり、新しい攻撃なので24秒にリセット。',
        },
      },
      refs: ['knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-082',
      quarter: 4,
      gameClockMs: 314000,
      type: 'throwIn',
      narration: '白のスローインでリスタート',
      team: 'A',
      shot: 'none',
      expect: {},
      refs: ['knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-083',
      quarter: 4,
      gameClockMs: 292000,
      type: 'fieldGoal',
      narration: '白10番がフローターを決めた！白に2点',
      team: 'A',
      playerNo: 10,
      points: 2,
      shot: 24,
      expect: {
        'sc-operator': {
          action: 'reset24',
          explanation: 'ゴール成功。赤の新しい攻撃が始まるので24秒にリセット。',
        },
        scorer: {
          kind: 'mark',
          mark: {
            cell: { kind: 'score', team: 'A', score: 31 },
            mark: { symbol: 'fg', playerNo: 10 },
            color: 'dark',
          },
          explanation: '白の累計31点目に／、番号欄に10。濃色ペン。',
        },
      },
      refs: ['knowledge/08-to-scoresheet', 'knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-084',
      quarter: 4,
      gameClockMs: 275000,
      type: 'steal',
      narration: '白のパスカットから赤4番がスティール！',
      team: 'B',
      playerNo: 4,
      shot: 24,
      expect: {
        'sc-operator': {
          action: 'reset24',
          explanation: 'スティールで新たなチーム（赤）がコントロール。即24秒にリセット。',
        },
      },
      refs: ['knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-085',
      quarter: 4,
      gameClockMs: 270000,
      type: 'fieldGoal',
      narration: 'そのまま赤4番が持ち込んでレイアップ！赤に2点',
      team: 'B',
      playerNo: 4,
      points: 2,
      shot: 24,
      expect: {
        'sc-operator': {
          action: 'reset24',
          explanation: 'ゴール成功。白の新しい攻撃が始まるので24秒にリセット。',
        },
        scorer: {
          kind: 'mark',
          mark: {
            cell: { kind: 'score', team: 'B', score: 32 },
            mark: { symbol: 'fg', playerNo: 4 },
            color: 'dark',
          },
          explanation: '赤の累計32点目に／、番号欄に4。濃色ペン。',
        },
      },
      refs: ['knowledge/08-to-scoresheet', 'knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-086',
      quarter: 4,
      gameClockMs: 150000,
      type: 'play',
      narration: '試合は白熱、両チーム一歩も譲らない展開が続く——',
      shot: 24,
      expect: {},
      refs: ['knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-087',
      quarter: 4,
      gameClockMs: 135000,
      type: 'jumpBallSituation',
      narration:
        '赤9番のドリブルに白5番が絡んでヘルドボール！矢印は赤方向なので赤ボールのスローイン',
      shot: 'none',
      expect: {
        'sc-operator': {
          action: 'keep',
          explanation:
            'APアローで赤ボールになるが、赤はもともとコントロールしていたチーム。SCは触らず継続。',
        },
        scorer: {
          kind: 'apArrow',
          to: 'A',
          explanation: '赤が矢印のスローインを使ったので、矢印を白方向へ反転させる。',
        },
      },
      refs: ['knowledge/08-to-scoresheet', 'knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-088',
      quarter: 4,
      gameClockMs: 135000,
      type: 'throwIn',
      narration: '赤のスローインでリスタート',
      team: 'B',
      shot: 'none',
      expect: {},
      refs: ['knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-089',
      quarter: 4,
      gameClockMs: 127000,
      type: 'fieldGoal',
      narration: '赤11番がターンアラウンドで決めた！赤に2点',
      team: 'B',
      playerNo: 11,
      points: 2,
      shot: 24,
      expect: {
        'sc-operator': {
          action: 'reset24',
          explanation: 'ゴール成功。白の新しい攻撃が始まるので24秒にリセット。',
        },
        scorer: {
          kind: 'mark',
          mark: {
            cell: { kind: 'score', team: 'B', score: 34 },
            mark: { symbol: 'fg', playerNo: 11 },
            color: 'dark',
          },
          explanation: '赤の累計34点目に／、番号欄に11。濃色ペン。',
        },
      },
      refs: ['knowledge/08-to-scoresheet', 'knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-090',
      quarter: 4,
      gameClockMs: 127000,
      type: 'timeout',
      narration: '3点差を追う白チームがタイムアウトを請求。認められました',
      team: 'A',
      shot: 'none',
      expect: {
        scorer: {
          kind: 'mark',
          mark: {
            cell: { kind: 'timeout', team: 'A', row: '第4Q', slot: 1 },
            mark: { symbol: 'timeout', value: 4 },
            color: 'dark',
          },
          explanation:
            '白の第4Q枠に経過分。残り2:07＝経過3分53秒 → 切り上げて「4」。濃色ペンで。',
        },
      },
      refs: ['knowledge/08-to-scoresheet'],
    },
    {
      id: 'ev-091',
      quarter: 4,
      gameClockMs: 127000,
      type: 'throwIn',
      narration: 'タイムアウト明け、白のスローインでリスタート',
      team: 'A',
      shot: 'none',
      expect: {},
      refs: ['knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-092',
      quarter: 4,
      gameClockMs: 105000,
      type: 'fieldGoal',
      narration: '白5番がコーナーから沈めて反撃！白に2点',
      team: 'A',
      playerNo: 5,
      points: 2,
      shot: 24,
      expect: {
        'sc-operator': {
          action: 'reset24',
          explanation: 'ゴール成功。赤の新しい攻撃が始まるので24秒にリセット。',
        },
        scorer: {
          kind: 'mark',
          mark: {
            cell: { kind: 'score', team: 'A', score: 33 },
            mark: { symbol: 'fg', playerNo: 5 },
            color: 'dark',
          },
          explanation: '白の累計33点目に／、番号欄に5。濃色ペン。',
        },
      },
      refs: ['knowledge/08-to-scoresheet', 'knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-093',
      quarter: 4,
      gameClockMs: 83000,
      type: 'violation',
      narration: '攻め急いだ赤5番、痛恨のトラベリング！白ボールに',
      team: 'B',
      playerNo: 5,
      shot: 24,
      expect: {
        'sc-operator': {
          action: 'reset24',
          explanation: 'トラベリングで攻守交代。白の新しい攻撃なので24秒にリセット。',
        },
      },
      refs: ['knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-094',
      quarter: 4,
      gameClockMs: 61000,
      type: 'fieldGoal',
      narration: '白7番、値千金のジャンプシュートで逆転！白に2点、35対34',
      team: 'A',
      playerNo: 7,
      points: 2,
      shot: 24,
      expect: {
        'sc-operator': {
          action: 'reset24',
          explanation: 'ゴール成功。赤の新しい攻撃が始まるので24秒にリセット。',
        },
        scorer: {
          kind: 'mark',
          mark: {
            cell: { kind: 'score', team: 'A', score: 35 },
            mark: { symbol: 'fg', playerNo: 7 },
            color: 'dark',
          },
          explanation: '白の累計35点目に／、番号欄に7。濃色ペン。',
        },
      },
      refs: ['knowledge/08-to-scoresheet', 'knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-095',
      quarter: 4,
      gameClockMs: 39000,
      type: 'violation',
      narration: '焦った赤9番にトラベリングの笛！白ボールに',
      team: 'B',
      playerNo: 9,
      shot: 24,
      expect: {
        'sc-operator': {
          action: 'reset24',
          explanation: 'トラベリングで攻守交代。白の新しい攻撃なので24秒にリセット。',
        },
      },
      refs: ['knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-096',
      quarter: 4,
      gameClockMs: 39000,
      type: 'throwIn',
      narration: '白のスローインでリスタート',
      team: 'A',
      shot: 'none',
      expect: {},
      refs: ['knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-097',
      quarter: 4,
      gameClockMs: 17000,
      type: 'fieldGoal',
      narration: '白10番がダメ押しの2点！37対34と突き放す',
      team: 'A',
      playerNo: 10,
      points: 2,
      shot: 24,
      expect: {
        'sc-operator': {
          action: 'reset24',
          explanation: 'ゴール成功。赤の新しい攻撃が始まるので24秒にリセット。',
        },
        scorer: {
          kind: 'mark',
          mark: {
            cell: { kind: 'score', team: 'A', score: 37 },
            mark: { symbol: 'fg', playerNo: 10 },
            color: 'dark',
          },
          explanation: '白の累計37点目に／、番号欄に10。濃色ペン。',
        },
      },
      refs: ['knowledge/08-to-scoresheet', 'knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-098',
      quarter: 4,
      gameClockMs: 0,
      type: 'periodEnd',
      narration: '試合終了のブザー！37対34、白チームの勝利！',
      shot: 'hide',
      expect: {
        scorer: {
          kind: 'mark',
          mark: {
            cell: { kind: 'score', team: 'A', score: 37 },
            mark: { symbol: 'closeGame' },
            color: 'dark',
          },
          explanation:
            'ゲーム終了は最後の得点（白の37点目）を太い○で囲み、太い横線を2本。未使用のランニングスコア列に斜線、最終スコア・勝者・終了時刻も記入する。濃色ペン。',
        },
      },
      refs: ['knowledge/08-to-scoresheet'],
    },
  ],
}
