import type { GameScript } from '../types'

/**
 * U12・第1Qのゲーム台本（白=Aチーム / 赤=Bチーム）。
 * 根拠: knowledge/08-to-scoresheet（記入・APアロー）、knowledge/09-to-timer-shotclock（SC操作）
 * atMs と gameClockMs の整合・SC切れ・ファウル枠・得点累計は validate-content が機械検証する。
 * 白: 4(→10と交代), 5, 6, 7, 8 ／ 赤: 4, 5, 6, 9, 11
 */
export const q1U12Script: GameScript = {
  id: 'sim-q1-u12',
  title: '第1Q通しプレイ（U12）',
  description:
    'ジャンプボールからブザーまで、U12の第1Q（6分）をリアルタイムで再生。自分の役割の仕事だけを操作して、見逃しゼロを目指す。',
  ruleset: 'u12',
  quarter: 1,
  quarterMs: 360000,
  ruleYear: 2026,
  events: [
    {
      id: 'ev-001',
      atMs: 0,
      gameClockMs: 360000,
      type: 'periodStart',
      narration:
        'ジャンプボール！トスが上がり、白7番がタップして白チームが最初のコントロール。第1Qスタート！',
      team: 'A',
      playerNo: 7,
      clock: { game: 'start', shot: 24 },
      expect: {
        'sc-operator': { action: 'reset24' },
        scorer: { kind: 'apArrow', to: 'B' },
      },
      refs: ['knowledge/08-to-scoresheet', 'knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-002',
      atMs: 21000,
      gameClockMs: 339000,
      type: 'fieldGoal',
      narration: '白7番、ドライブからレイアップ成功！白に2点',
      team: 'A',
      playerNo: 7,
      points: 2,
      clock: { game: 'none', shot: 24 },
      expect: {
        'sc-operator': { action: 'reset24' },
        scorer: {
          kind: 'mark',
          mark: {
            cell: { kind: 'score', team: 'A', score: 2 },
            mark: { symbol: 'fg', playerNo: 7 },
            color: 'red',
          },
        },
      },
      refs: ['knowledge/08-to-scoresheet', 'knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-003',
      atMs: 43000,
      gameClockMs: 317000,
      type: 'fieldGoal',
      narration: '赤5番がミドルシュートを沈める！赤に2点',
      team: 'B',
      playerNo: 5,
      points: 2,
      clock: { game: 'none', shot: 24 },
      expect: {
        'sc-operator': { action: 'reset24' },
        scorer: {
          kind: 'mark',
          mark: {
            cell: { kind: 'score', team: 'B', score: 2 },
            mark: { symbol: 'fg', playerNo: 5 },
            color: 'red',
          },
        },
      },
      refs: ['knowledge/08-to-scoresheet', 'knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-004',
      atMs: 64000,
      gameClockMs: 296000,
      type: 'steal',
      narration: '白のパスを赤4番がスティール！そのまま前へ持ち込む',
      team: 'B',
      playerNo: 4,
      clock: { game: 'none', shot: 24 },
      expect: {
        'sc-operator': { action: 'reset24' },
      },
      refs: ['knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-005',
      atMs: 70000,
      gameClockMs: 290000,
      type: 'fieldGoal',
      narration: '速攻から赤9番がレイアップ成功！赤に2点',
      team: 'B',
      playerNo: 9,
      points: 2,
      clock: { game: 'none', shot: 24 },
      expect: {
        'sc-operator': { action: 'reset24' },
        scorer: {
          kind: 'mark',
          mark: {
            cell: { kind: 'score', team: 'B', score: 4 },
            mark: { symbol: 'fg', playerNo: 9 },
            color: 'red',
          },
        },
      },
      refs: ['knowledge/08-to-scoresheet', 'knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-006',
      atMs: 78000,
      gameClockMs: 282000,
      type: 'outOfBounds',
      narration: '白のパスを赤6番がタップしてボールはアウトオブバウンズ。白ボールのスローイン',
      team: 'A',
      clock: { game: 'stop', shot: 'none' },
      expect: {
        'sc-operator': { action: 'keep' },
      },
      refs: ['knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-007',
      atMs: 84000,
      gameClockMs: 282000,
      type: 'throwIn',
      narration: '白のスローインでリスタート',
      team: 'A',
      clock: { game: 'start', shot: 'none' },
      expect: {},
      refs: ['knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-008',
      atMs: 92000,
      gameClockMs: 274000,
      type: 'foul',
      narration: 'シュートに行った白5番に赤4番がファウル！フリースロー2本',
      team: 'B',
      playerNo: 4,
      clock: { game: 'stop', shot: 'hide' },
      expect: {
        'sc-operator': { action: 'reset24' },
        scorer: {
          kind: 'mark',
          mark: {
            cell: { kind: 'foul', team: 'B', row: '4', slot: 1 },
            mark: { symbol: 'P', subscript: 2 },
            color: 'red',
          },
        },
      },
      refs: ['knowledge/08-to-scoresheet', 'knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-009',
      atMs: 105000,
      gameClockMs: 274000,
      type: 'freeThrow',
      narration: '白5番のフリースロー1本目……成功！白に1点',
      team: 'A',
      playerNo: 5,
      points: 1,
      clock: { game: 'none', shot: 'none' },
      expect: {
        scorer: {
          kind: 'mark',
          mark: {
            cell: { kind: 'score', team: 'A', score: 3 },
            mark: { symbol: 'ft', playerNo: 5 },
            color: 'red',
          },
        },
      },
      refs: ['knowledge/08-to-scoresheet'],
    },
    {
      id: 'ev-010',
      atMs: 113000,
      gameClockMs: 274000,
      type: 'freeThrow',
      narration: 'フリースロー2本目も成功！白に1点。次は赤ボール',
      team: 'A',
      playerNo: 5,
      points: 1,
      clock: { game: 'none', shot: 24 },
      expect: {
        'sc-operator': { action: 'reset24' },
        scorer: {
          kind: 'mark',
          mark: {
            cell: { kind: 'score', team: 'A', score: 4 },
            mark: { symbol: 'ft', playerNo: 5 },
            color: 'red',
          },
        },
      },
      refs: ['knowledge/08-to-scoresheet', 'knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-011',
      atMs: 119000,
      gameClockMs: 274000,
      type: 'throwIn',
      narration: '赤のエンドラインスローインでリスタート',
      team: 'B',
      clock: { game: 'start', shot: 'none' },
      expect: {},
      refs: ['knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-012',
      atMs: 140000,
      gameClockMs: 253000,
      type: 'rebound',
      narration: '赤11番のシュートはリングに当たって外れる……赤9番がオフェンスリバウンド！',
      team: 'B',
      playerNo: 9,
      clock: { game: 'none', shot: 14 },
      expect: {
        'sc-operator': { action: 'reset14' },
      },
      refs: ['knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-013',
      atMs: 147000,
      gameClockMs: 246000,
      type: 'fieldGoal',
      narration: '赤9番がそのままねじ込んだ！赤に2点',
      team: 'B',
      playerNo: 9,
      points: 2,
      clock: { game: 'none', shot: 24 },
      expect: {
        'sc-operator': { action: 'reset24' },
        scorer: {
          kind: 'mark',
          mark: {
            cell: { kind: 'score', team: 'B', score: 6 },
            mark: { symbol: 'fg', playerNo: 9 },
            color: 'red',
          },
        },
      },
      refs: ['knowledge/08-to-scoresheet', 'knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-014',
      atMs: 169000,
      gameClockMs: 224000,
      type: 'violation',
      narration: '白7番、トラベリングの笛！赤ボールに',
      team: 'A',
      playerNo: 7,
      clock: { game: 'stop', shot: 24 },
      expect: {
        'sc-operator': { action: 'reset24' },
      },
      refs: ['knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-015',
      atMs: 174000,
      gameClockMs: 224000,
      type: 'substitution',
      narration: '白チームが交代。4番に代わって10番がコートへ',
      team: 'A',
      playerNo: 10,
      clock: { game: 'none', shot: 'none' },
      expect: {},
      refs: ['knowledge/07-to-basics'],
    },
    {
      id: 'ev-016',
      atMs: 180000,
      gameClockMs: 224000,
      type: 'throwIn',
      narration: '赤のスローインでリスタート',
      team: 'B',
      clock: { game: 'start', shot: 'none' },
      expect: {},
      refs: ['knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-017',
      atMs: 202000,
      gameClockMs: 202000,
      type: 'fieldGoal',
      narration: '赤5番、カットインから決めた！赤に2点',
      team: 'B',
      playerNo: 5,
      points: 2,
      clock: { game: 'none', shot: 24 },
      expect: {
        'sc-operator': { action: 'reset24' },
        scorer: {
          kind: 'mark',
          mark: {
            cell: { kind: 'score', team: 'B', score: 8 },
            mark: { symbol: 'fg', playerNo: 5 },
            color: 'red',
          },
        },
      },
      refs: ['knowledge/08-to-scoresheet', 'knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-018',
      atMs: 206000,
      gameClockMs: 198000,
      type: 'timeout',
      narration: '白チームがタイムアウトを請求。認められました',
      team: 'A',
      clock: { game: 'stop', shot: 'none' },
      expect: {
        scorer: {
          kind: 'mark',
          mark: {
            cell: { kind: 'timeout', team: 'A', row: '第1Q', slot: 1 },
            mark: { symbol: 'timeout', value: 3 },
            color: 'red',
          },
        },
      },
      refs: ['knowledge/08-to-scoresheet'],
    },
    {
      id: 'ev-019',
      atMs: 223000,
      gameClockMs: 198000,
      type: 'throwIn',
      narration: 'タイムアウト明け、白のスローインでリスタート',
      team: 'A',
      clock: { game: 'start', shot: 24 },
      expect: {},
      refs: ['knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-020',
      atMs: 244000,
      gameClockMs: 177000,
      type: 'fieldGoal',
      narration: '白10番、ゴール下で決めた！白に2点',
      team: 'A',
      playerNo: 10,
      points: 2,
      clock: { game: 'none', shot: 24 },
      expect: {
        'sc-operator': { action: 'reset24' },
        scorer: {
          kind: 'mark',
          mark: {
            cell: { kind: 'score', team: 'A', score: 6 },
            mark: { symbol: 'fg', playerNo: 10 },
            color: 'red',
          },
        },
      },
      refs: ['knowledge/08-to-scoresheet', 'knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-021',
      atMs: 254000,
      gameClockMs: 167000,
      type: 'jumpBallSituation',
      narration:
        '白5番と赤9番がボールを奪い合ってヘルドボール！矢印は赤方向、赤ボールのスローインへ',
      clock: { game: 'stop', shot: 'none' },
      expect: {
        'sc-operator': { action: 'keep' },
        scorer: { kind: 'apArrow', to: 'A' },
      },
      refs: ['knowledge/08-to-scoresheet', 'knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-022',
      atMs: 260000,
      gameClockMs: 167000,
      type: 'throwIn',
      narration: '赤のスローインでリスタート',
      team: 'B',
      clock: { game: 'start', shot: 'none' },
      expect: {},
      refs: ['knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-023',
      atMs: 272000,
      gameClockMs: 155000,
      type: 'fieldGoal',
      narration: '赤11番がジャンプシュート成功！赤に2点',
      team: 'B',
      playerNo: 11,
      points: 2,
      clock: { game: 'none', shot: 24 },
      expect: {
        'sc-operator': { action: 'reset24' },
        scorer: {
          kind: 'mark',
          mark: {
            cell: { kind: 'score', team: 'B', score: 10 },
            mark: { symbol: 'fg', playerNo: 11 },
            color: 'red',
          },
        },
      },
      refs: ['knowledge/08-to-scoresheet', 'knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-024',
      atMs: 294000,
      gameClockMs: 133000,
      type: 'foul',
      narration: 'ドリブルする白7番に赤6番が手を出してファウル。白ボールのスローイン（FTなし）',
      team: 'B',
      playerNo: 6,
      clock: { game: 'stop', shot: 24 },
      expect: {
        'sc-operator': { action: 'reset24' },
        scorer: {
          kind: 'mark',
          mark: {
            cell: { kind: 'foul', team: 'B', row: '6', slot: 1 },
            mark: { symbol: 'P' },
            color: 'red',
          },
        },
      },
      refs: ['knowledge/08-to-scoresheet', 'knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-025',
      atMs: 300000,
      gameClockMs: 133000,
      type: 'throwIn',
      narration: '白のスローインでリスタート',
      team: 'A',
      clock: { game: 'start', shot: 'none' },
      expect: {},
      refs: ['knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-026',
      atMs: 323000,
      gameClockMs: 110000,
      type: 'fieldGoal',
      narration: '白5番、ショットクロックぎりぎりでジャンプシュート成功！白に2点',
      team: 'A',
      playerNo: 5,
      points: 2,
      clock: { game: 'none', shot: 24 },
      expect: {
        'sc-operator': { action: 'reset24' },
        scorer: {
          kind: 'mark',
          mark: {
            cell: { kind: 'score', team: 'A', score: 8 },
            mark: { symbol: 'fg', playerNo: 5 },
            color: 'red',
          },
        },
      },
      refs: ['knowledge/08-to-scoresheet', 'knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-027',
      atMs: 346000,
      gameClockMs: 87000,
      type: 'violation',
      narration: '赤11番、ダブルドリブルの笛！白ボールに',
      team: 'B',
      playerNo: 11,
      clock: { game: 'stop', shot: 24 },
      expect: {
        'sc-operator': { action: 'reset24' },
      },
      refs: ['knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-028',
      atMs: 352000,
      gameClockMs: 87000,
      type: 'throwIn',
      narration: '白のスローインでリスタート',
      team: 'A',
      clock: { game: 'start', shot: 'none' },
      expect: {},
      refs: ['knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-029',
      atMs: 375000,
      gameClockMs: 64000,
      type: 'fieldGoal',
      narration: '白7番が今日3本目のシュートを決めた！白に2点',
      team: 'A',
      playerNo: 7,
      points: 2,
      clock: { game: 'none', shot: 24 },
      expect: {
        'sc-operator': { action: 'reset24' },
        scorer: {
          kind: 'mark',
          mark: {
            cell: { kind: 'score', team: 'A', score: 10 },
            mark: { symbol: 'fg', playerNo: 7 },
            color: 'red',
          },
        },
      },
      refs: ['knowledge/08-to-scoresheet', 'knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-030',
      atMs: 397000,
      gameClockMs: 42000,
      type: 'fieldGoal',
      narration: '赤4番がドライブで切り込んで決めた！赤に2点',
      team: 'B',
      playerNo: 4,
      points: 2,
      clock: { game: 'none', shot: 24 },
      expect: {
        'sc-operator': { action: 'reset24' },
        scorer: {
          kind: 'mark',
          mark: {
            cell: { kind: 'score', team: 'B', score: 12 },
            mark: { symbol: 'fg', playerNo: 4 },
            color: 'red',
          },
        },
      },
      refs: ['knowledge/08-to-scoresheet', 'knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-031',
      atMs: 420000,
      gameClockMs: 19000,
      type: 'fieldGoal',
      narration: '白10番、コーナーから決めた！白に2点',
      team: 'A',
      playerNo: 10,
      points: 2,
      clock: { game: 'none', shot: 24 },
      expect: {
        'sc-operator': { action: 'reset24' },
        scorer: {
          kind: 'mark',
          mark: {
            cell: { kind: 'score', team: 'A', score: 12 },
            mark: { symbol: 'fg', playerNo: 10 },
            color: 'red',
          },
        },
      },
      refs: ['knowledge/08-to-scoresheet', 'knowledge/09-to-timer-shotclock'],
    },
    {
      id: 'ev-032',
      atMs: 439000,
      gameClockMs: 0,
      type: 'periodEnd',
      narration: 'ブザーが鳴って第1Q終了！12対12の同点',
      clock: { game: 'stop', shot: 'hide' },
      expect: {
        scorer: {
          kind: 'mark',
          mark: {
            cell: { kind: 'score', team: 'A', score: 12 },
            mark: { symbol: 'closeQ' },
            color: 'red',
          },
        },
      },
      refs: ['knowledge/08-to-scoresheet'],
    },
  ],
}
