import type { Question } from '../types'

/** TOの基礎・共通事項（TOサポーター中心） */
export const toBasicsQuestions: Question[] = [
  {
    id: 'tb-001',
    domain: 'to-basics',
    roles: ['to-supporter', 'a-scorer'],
    ruleset: 'both',
    difficulty: 1,
    type: 'single',
    prompt: 'TO4人構成のうち、スコアボードの操作とファウルの表示を担当するのは？',
    choices: ['スコアラー', 'アシスタントスコアラー', 'タイマー', 'ショットクロックオペレーター'],
    answer: 1,
    explanation:
      'Aスコアラーはスコアボードの操作・ファウルの表示・スコアラーのサポートを担当する。スコアラーはスコアシートの記録・合図・APアロー、タイマーはゲームクロック、SCオペレーターはショットクロック。',
    refs: ['JBA TOマニュアル 第2章', 'knowledge/07-to-basics'],
    ruleYear: 2026,
  },
  {
    id: 'tb-002',
    domain: 'to-basics',
    roles: ['to-supporter', 'scorer', 'timer'],
    ruleset: 'both',
    difficulty: 2,
    type: 'truefalse',
    prompt: 'TOのブザーが鳴ると、その瞬間にボールはデッドになりゲームは止まる。',
    answer: false,
    explanation:
      'ブザーはゲームクロックやゲームを止めるものではなく、ボールをデッドにするものでもない。審判が笛を鳴らして初めてゲームが止まる。だからこそブザーは慎重に使う。',
    refs: ['JBA TOマニュアル 第3章', 'knowledge/07-to-basics'],
    ruleYear: 2026,
  },
  {
    id: 'tb-003',
    domain: 'to-basics',
    roles: ['to-supporter', 'scorer'],
    ruleset: 'u12',
    difficulty: 2,
    type: 'single',
    prompt: 'U12国内大会でチームリストの提出期限は、ゲーム開始の何分前まで？',
    choices: ['40分前', '30分前', '20分前', '10分前'],
    answer: 1,
    explanation:
      'U12国内は開始30分前まで（FIBA基準の一般は40分前）。開始10分前までには両HCがメンバー・スターターを確認してスコアシートにサインする（チームA→Bの順）。',
    refs: ['U12 TOハンドブック', 'knowledge/07-to-basics'],
    ruleYear: 2026,
  },
  {
    id: 'tb-004',
    domain: 'to-basics',
    roles: ['to-supporter', 'timer'],
    ruleset: 'both',
    difficulty: 2,
    type: 'single',
    prompt: 'ゲーム開始前、タイマーがブザーを鳴らすタイミングは？',
    choices: [
      '開始5分前と1分前',
      '開始3分前と1分30秒前',
      '開始2分前と30秒前',
    ],
    answer: 1,
    explanation:
      '開始3分前（審判は3本指のシグナル）と1分30秒前（審判が笛、両チームはベンチエリアへ）にブザーを鳴らす。審判がコートにいる間にショットクロックのブザー音を聞かせておく点検も忘れずに。',
    refs: ['JBA TOマニュアル 第3章', 'knowledge/07-to-basics'],
    ruleYear: 2026,
  },
  {
    id: 'tb-005',
    domain: 'to-basics',
    roles: ['to-supporter'],
    ruleset: 'u12',
    difficulty: 1,
    type: 'single',
    prompt: 'U12における「TOサポーター」の役割は？',
    choices: [
      'TOの4人目としてテーブルに座り、記録を分担する',
      'TOを務める子どもたちをテーブルの後ろから見守り、手助けする大人',
      '審判の補助としてコートサイドに立つ',
    ],
    answer: 1,
    explanation:
      'U12ではプレーヤー（子どもたち）自身がTOを務めることが推奨されており、TOサポーターはテーブルの後ろから見守り手助けする大人。ミスは責めずに原因分析と再発防止、前向きな声かけが心得。',
    refs: ['U12 TOサポーターマニュアル', 'knowledge/07-to-basics'],
    ruleYear: 2026,
  },
  {
    id: 'tb-006',
    domain: 'to-basics',
    roles: ['to-supporter'],
    ruleset: 'u12',
    difficulty: 3,
    type: 'single',
    prompt: 'TO主任・TOサポーターがスコアラーの代わりにブザーを鳴らしてよい例外は？',
    choices: [
      '子どもが操作に迷っているときはいつでも',
      '最後の2分間で、ゴール後のタイムアウト／交代請求にスコアラーが対応できないときのみ',
      '例外はなく、絶対に鳴らしてはいけない',
    ],
    answer: 1,
    explanation:
      'スコアラーの代わりにジェスチャーやブザーを行うことは厳に慎むのが原則。唯一の例外はL2M（最後の2分）でゴール後のタイムアウト／交代請求にスコアラーが対応できないときにTO主任がブザーを鳴らせること。',
    refs: ['TO主任マニュアル', 'knowledge/07-to-basics'],
    ruleYear: 2026,
  },
  {
    id: 'tb-007',
    domain: 'to-basics',
    roles: ['to-supporter'],
    ruleset: 'both',
    difficulty: 2,
    type: 'truefalse',
    prompt: '対処に困るトラブルが起きたら、プレー中でもブザーを鳴らして審判を呼んでよい。',
    answer: false,
    explanation:
      'プレー中に審判を呼ぶブザーは鳴らさない。トラブルはプレーが止まっているときに審判を呼ぶ。審判を呼ぶ前に「何が起きたか」を正確に把握してから伝えるのも鉄則。',
    refs: ['TO主任マニュアル', 'knowledge/07-to-basics'],
    ruleYear: 2026,
  },
  {
    id: 'tb-008',
    domain: 'to-basics',
    roles: ['to-supporter'],
    ruleset: 'both',
    difficulty: 1,
    type: 'truefalse',
    prompt: 'TOはオフィシャルチームの一員なので、応援や判定への感情表現はしない。',
    answer: true,
    explanation:
      'TOはニュートラルな立場。応援や感情表現はせず、審判の判定に異を唱えるシグナルも絶対に送らない。不明な点は審判に短く明確に告げて確認する。',
    refs: ['JBA TOマニュアル 第3章', 'knowledge/07-to-basics'],
    ruleYear: 2026,
  },
  {
    id: 'tb-009',
    domain: 'to-basics',
    roles: ['scorer', 'a-scorer', 'to-supporter'],
    ruleset: 'both',
    difficulty: 1,
    type: 'single',
    prompt: '審判からのファウルのレポートを受けるときの正しい流れは？',
    choices: [
      'メモを取りながら黙って聞く',
      'アイコンタクト→同時復唱→サムアップ（OKサイン）',
      '大きな声で番号を復唱して立ち上がる',
    ],
    answer: 1,
    explanation:
      'ファウルのレポートはアイコンタクト→審判と同時に復唱→サムアップで受ける。番号が聞き取れない・間違っていそうなときは曖昧なまま記入せず、すぐ審判を呼んで確認する。',
    refs: ['JBA TOマニュアル 第3章', 'knowledge/07-to-basics'],
    ruleYear: 2026,
  },
  {
    id: 'tb-010',
    domain: 'to-basics',
    roles: ['scorer', 'to-supporter'],
    ruleset: 'both',
    difficulty: 2,
    type: 'single',
    prompt: 'ゲーム終了後のスコアシートへのサインの順番は？',
    choices: [
      'クルーチーフ→アンパイア→TO全員',
      'TO全員→アンパイア→クルーチーフが最後に点検して承認サイン',
      'アンパイア→クルーチーフ→TO全員',
    ],
    answer: 1,
    explanation:
      'TO全員→アンパイア→最後にクルーチーフが点検・承認してサインの順。クルーチーフのサインでオフィシャルチームの管理権限が終了する（＝記録の訂正もここまで）。',
    refs: ['JBA TOマニュアル 第3章', 'knowledge/07-to-basics'],
    ruleYear: 2026,
  },
  {
    id: 'tb-011',
    domain: 'to-basics',
    roles: ['scorer', 'timer'],
    ruleset: 'both',
    difficulty: 2,
    type: 'single',
    prompt: 'タイムアウト・交代の審判への合図はどう行う？',
    choices: [
      '立ち上がって大きな声で伝える',
      '座ったまま、ブザーとジェスチャーだけで行う',
      'テーブルを離れて審判に直接伝える',
    ],
    answer: 1,
    explanation:
      '合図は座ったままブザーとジェスチャーだけで行う（声は出さない）。声出しはTOクルー同士のコミュニケーション用。タイムアウトはTの形＋請求チームのベンチを指す、交代は両手を顔の前で交差する。',
    refs: ['JBA TOマニュアル 第3章', 'knowledge/07-to-basics'],
    ruleYear: 2026,
  },
  {
    id: 'tb-012',
    domain: 'to-basics',
    roles: ['to-supporter', 'a-scorer'],
    ruleset: 'both',
    difficulty: 3,
    type: 'single',
    prompt: 'コート上でファイティングが起きたとき、アウェーチームのベンチを注視するのは誰？',
    choices: ['スコアラー', 'アシスタントスコアラー', 'タイマー', 'ショットクロックオペレーター'],
    answer: 1,
    explanation:
      '視野分担は、Aスコアラー＝アウェーベンチ、SCオペレーター＝ホームベンチ、スコアラーとタイマー＝コート上。該当者と時間を個々に記録し、審判の報告書作成をサポートする。',
    refs: ['JBA TOマニュアル 第3章', 'knowledge/07-to-basics'],
    ruleYear: 2026,
  },
  {
    id: 'tb-013',
    domain: 'to-basics',
    roles: ['to-supporter'],
    ruleset: 'u12',
    difficulty: 3,
    type: 'single',
    prompt: 'U12ハンドブックのTOテーブルの座席配置。Aチームベンチ側からの順番は？',
    choices: [
      'スコアラー → Aスコアラー → タイマー → SCオペレーター',
      'SCオペレーター → タイマー → スコアラー → Aスコアラー',
      'タイマー → SCオペレーター → Aスコアラー → スコアラー',
    ],
    answer: 1,
    explanation:
      'Aチームベンチ側からショットクロックオペレーター→タイマー→スコアラー→Aスコアラーの順。座席はコート両チームベンチの間、テーブル中央部に位置する。',
    refs: ['U12 TOハンドブック', 'knowledge/07-to-basics'],
    ruleYear: 2026,
  },
  {
    id: 'tb-014',
    domain: 'to-basics',
    roles: ['to-supporter'],
    ruleset: 'u12',
    difficulty: 2,
    type: 'truefalse',
    prompt: 'U12・U15のゲームでは、大会主催者の判断でTOに補助員1名を追加した5人体制にできる。',
    answer: true,
    explanation:
      'TOは4人構成（スコアラー・Aスコアラー・タイマー・SCオペレーター）が基本だが、U12・U15では主催者判断で補助員1名を追加できる。U12ではさらに後ろにTO主任・TOサポーターの席を設けることがある。',
    refs: ['JBA TOマニュアル 第2章', 'knowledge/07-to-basics'],
    ruleYear: 2026,
  },
  {
    id: 'tb-015',
    domain: 'to-basics',
    roles: ['to-supporter', 'a-scorer'],
    ruleset: 'both',
    difficulty: 2,
    type: 'truefalse',
    prompt: 'アシスタントスコアラーは最近の規則改定で廃止され、現行の競技規則には存在しない。',
    answer: false,
    explanation:
      '誤解。競技規則には第48条「スコアラー、アシスタントスコアラー：任務」が現存し、国内大会での分担（ファウル表示器具の操作など）も明記されている。ローカル大会でTOを3人や2人で回す運用があるだけで、「その大会にAスコアラー席がない」≠「規則から消えた」。',
    refs: ['競技規則 第48・49条', 'knowledge/07-to-basics'],
    ruleYear: 2026,
  },
  {
    id: 'tb-016',
    domain: 'to-basics',
    roles: ['to-supporter'],
    ruleset: 'both',
    difficulty: 2,
    type: 'single',
    prompt: 'ゲーム前のTOミーティングで確認する内容として適切でないのは？',
    choices: [
      '重大な場面（得点・タイムアウト・交代・Q終了・AP等）での対応方法',
      '機器の位置と誤作動時の対応',
      '今日の両チームの実力差と予想スコア',
    ],
    answer: 2,
    explanation:
      'TOミーティングでは開始時刻、規則の最新変更点、重大な場面での対応、機器の位置と誤作動時の対応、審判とのコミュニケーション方法を確認する。チームの実力の予想はTOの仕事と関係なく、ニュートラルの立場にも反する。',
    refs: ['JBA TOマニュアル 第3章', 'knowledge/07-to-basics'],
    ruleYear: 2026,
  },
  {
    id: 'tb-017',
    domain: 'to-basics',
    roles: ['sc-operator', 'timer', 'to-supporter'],
    ruleset: 'both',
    difficulty: 1,
    type: 'single',
    prompt: '審判が「人差し指を伸ばして手を回す」シグナルを出した。意味は？',
    choices: [
      'ゲームクロックをスタートせよ',
      'ショットクロックをリセットせよ',
      'タイムアウトを開始せよ',
    ],
    answer: 1,
    explanation:
      '人差し指を回すのはショットクロックのリセット（コントロールが変わった／ボールがリングに触れた）。手を振り下ろすのはクロックスタート、サムアップはOKのコミュニケーション。',
    refs: ['JBA TOマニュアル 第3章', 'knowledge/07-to-basics'],
    ruleYear: 2026,
  },
  {
    id: 'tb-018',
    domain: 'to-basics',
    roles: ['scorer', 'to-supporter'],
    ruleset: 'both',
    difficulty: 2,
    type: 'single',
    prompt: 'Q終わりの得点が入ったかどうかについて審判から確認を求められた。TOの対応は？',
    choices: [
      '見えた人が全員でそれぞれ説明する',
      '事実のみを1人が代表して伝える（ジェスチャーや大声は使わない）',
      '「入っていたと思います」と推測も含めて伝える',
    ],
    answer: 1,
    explanation:
      '不明確な状況の確認要請には、事実のみを1人が代表して伝える。推測を混ぜない・全員で話さない・ジェスチャーや大声を使わない。審判を「判断のできない状況」に追い込まないのが原則。',
    refs: ['JBA TOマニュアル 第3章', 'knowledge/07-to-basics'],
    ruleYear: 2026,
  },
  {
    id: 'tb-019',
    domain: 'to-basics',
    roles: ['to-supporter', 'timer'],
    ruleset: 'both',
    difficulty: 2,
    type: 'single',
    prompt: '機器の誤作動に気づいた。審判に知らせるタイミングは？',
    choices: [
      '気づいた瞬間にブザーで知らせる',
      '規則に定められたタイミング＝ボールがデッドのときに知らせる',
      'ゲーム終了後にまとめて報告する',
    ],
    answer: 1,
    explanation:
      '機器の誤作動はボールデッド時に審判に知らせる（プレー中にゲームを止めない）。それまでは経過時間の計測などできる対応を続ける。',
    refs: ['JBA TOマニュアル 第3章', 'knowledge/07-to-basics'],
    ruleYear: 2026,
  },
  {
    id: 'tb-020',
    domain: 'to-basics',
    roles: ['to-supporter', 'scorer'],
    ruleset: 'both',
    difficulty: 2,
    type: 'truefalse',
    prompt: 'ゲーム終了後、TOは会場を離れる前に審判・コミッショナーに許可を求める。',
    answer: true,
    explanation:
      '終了後はスコアシートの完成→サイン（TO全員→アンパイア→クルーチーフ）→コピーのチーム返却まで行い、会場を離れる前に審判・コミッショナーに許可を求める。終了後に何か起きたら観察・記録して報告書作成を手伝う。',
    refs: ['JBA TOマニュアル 第3章', 'knowledge/07-to-basics'],
    ruleYear: 2026,
  },
]
