import type { Question } from '../types'

/** クロック操作（タイマー・ショットクロックオペレーター） */
export const toClockQuestions: Question[] = [
  {
    id: 'tc-001',
    domain: 'to-clock',
    roles: ['timer', 'sc-operator'],
    ruleset: 'both',
    difficulty: 1,
    type: 'single',
    prompt:
      'スローインでゲームが再開される。タイマーがゲームクロックを動かし始めるのはいつ？',
    choices: [
      'スローインするプレーヤーにボールが与えられたとき',
      'スローインされたボールにコート上のプレーヤーが触れたとき',
      '審判が笛を鳴らしたとき',
      'ボールがコートのライン内に入ったとき',
    ],
    answer: 1,
    explanation:
      'ゲームクロックは「コート上のプレーヤーがボールに触れた（触れられた）とき」にスタートする。スローインするプレーヤーに与えられた瞬間はボールがライブになるだけで、まだクロックは動かさない。ショットクロックも同じ瞬間にスタートする。',
    refs: ['JBA TOマニュアル 第6章', 'knowledge/09-to-timer-shotclock'],
    ruleYear: 2026,
  },
  {
    id: 'tc-002',
    domain: 'to-clock',
    roles: ['timer'],
    ruleset: 'both',
    difficulty: 1,
    type: 'single',
    prompt: 'ゲーム開始のジャンプボール。ゲームクロックをスタートさせるのはいつ？',
    choices: [
      '審判がボールをトスした瞬間',
      'ジャンパーが正当にボールをタップしたとき',
      'タップされたボールを誰かが保持したとき',
    ],
    answer: 1,
    explanation:
      'ジャンプボールでは、ジャンパーが正当にボールをタップした瞬間にゲームクロックをスタートする。ショットクロックはこの瞬間ではなく、どちらかのチームがコントロールを得てからスタートする点が異なる。',
    refs: ['JBA TOマニュアル 第6章', 'knowledge/09-to-timer-shotclock'],
    ruleYear: 2026,
  },
  {
    id: 'tc-003',
    domain: 'to-clock',
    roles: ['timer'],
    ruleset: 'both',
    difficulty: 2,
    type: 'single',
    prompt:
      '最後のフリースローが不成功でボールはライブ。ゲームクロックをスタートさせるのはいつ？',
    choices: [
      'ボールがリングに触れたとき',
      'リングで弾んだボールにコート上のプレーヤーが触れたとき',
      '審判が笛を鳴らしたとき',
    ],
    answer: 1,
    explanation:
      '最後のFTが不成功でボールがライブのときは、リングで弾んだボールにコート上のプレーヤーが触れた瞬間にスタートする。リングに当たっただけではまだ動かさない。',
    refs: ['JBA TOマニュアル 第6章', 'knowledge/09-to-timer-shotclock'],
    ruleYear: 2026,
  },
  {
    id: 'tc-004',
    domain: 'to-clock',
    roles: ['timer', 'sc-operator'],
    ruleset: 'both',
    difficulty: 1,
    type: 'truefalse',
    prompt:
      'プレーヤーがボールに触れた瞬間がテーブルから確認できないときは、審判の「手を振り下ろす」シグナルに合わせてクロックをスタートしてよい。',
    answer: true,
    explanation:
      '触れた瞬間が確認できないときは、審判が手を振り下ろすシグナルがスタートの合図になる。審判のシグナルは常に確認する習慣をつける。',
    refs: ['JBA TOマニュアル 第6章', 'knowledge/09-to-timer-shotclock'],
    ruleYear: 2026,
  },
  {
    id: 'tc-005',
    domain: 'to-clock',
    roles: ['timer'],
    ruleset: 'u12',
    difficulty: 1,
    type: 'single',
    prompt: 'U12のタイムアウトの長さと、ブザーを鳴らすタイミングは？',
    choices: [
      '60秒。50秒経過時と60秒経過時にブザー',
      '45秒。35秒経過時と45秒経過時にブザー',
      '45秒。30秒経過時と45秒経過時にブザー',
      '60秒。45秒経過時と60秒経過時にブザー',
    ],
    answer: 1,
    explanation:
      'U12のタイムアウトは45秒で、35秒経過時と45秒経過時にブザーを鳴らす。一般は60秒（50秒・60秒でブザー）。',
    refs: ['U12適用規則 第18条', 'knowledge/09-to-timer-shotclock'],
    ruleYear: 2026,
  },
  {
    id: 'tc-006',
    domain: 'to-clock',
    roles: ['timer'],
    ruleset: 'both',
    difficulty: 2,
    type: 'single',
    prompt: 'タイムアウトの計測を始める起点はどれ？',
    choices: [
      'スコアラーがブザーを鳴らしたとき',
      'HCがタイムアウトを請求したとき',
      '審判が笛を鳴らしてタイムアウトのシグナルを示したとき',
      '両チームがベンチに入ったとき',
    ],
    answer: 2,
    explanation:
      'タイムアウトの計測は「審判が笛を鳴らしてタイムアウトのシグナルを示したとき」から。スコアラーのブザーが起点ではない。計測はゲームクロックとは別のストップウォッチで行う。',
    refs: ['JBA TOマニュアル 第6章', 'knowledge/09-to-timer-shotclock'],
    ruleYear: 2026,
  },
  {
    id: 'tc-007',
    domain: 'to-clock',
    roles: ['timer'],
    ruleset: 'u12',
    difficulty: 2,
    type: 'single',
    prompt: 'U12のQ1-Q2間・Q3-Q4間のインターバルの長さとブザーは？',
    choices: [
      '2分。終了30秒前にブザー',
      '1分。終了30秒前にブザー',
      '1分。途中のブザーなし、終了時のみ',
      '2分。終了1分前にブザー',
    ],
    answer: 2,
    explanation:
      'U12のクォーター間インターバルは1分で、途中のブザーはなく終了時のみ鳴らす。一般は2分で終了30秒前にブザー。終了したらゲームクロックを次のQの時間（U12は6:00）にリセットする。',
    refs: ['U12適用規則 第8条', 'knowledge/09-to-timer-shotclock'],
    ruleYear: 2026,
  },
  {
    id: 'tc-008',
    domain: 'to-clock',
    roles: ['timer'],
    ruleset: 'u12',
    difficulty: 2,
    type: 'single',
    prompt: 'U12のハーフタイムの長さと、ブザーを鳴らすタイミングは？',
    choices: [
      '10分。終了3分前と1分30秒前にブザー',
      '5分。終了3分前と1分前にブザー',
      '5分。終了1分前のみブザー',
      '15分。終了3分前と1分30秒前にブザー',
    ],
    answer: 1,
    explanation:
      'U12のハーフタイムは5分で、終了3分前と1分前にブザーを鳴らす。一般の国内推奨は10分（3分前・1分30秒前にブザー）。',
    refs: ['U12適用規則 第8条', 'knowledge/09-to-timer-shotclock'],
    ruleYear: 2026,
  },
  {
    id: 'tc-009',
    domain: 'to-clock',
    roles: ['timer'],
    ruleset: 'u12',
    difficulty: 2,
    type: 'truefalse',
    prompt:
      'U12のゲームでも、第4Q残り2分以下はフィールドゴール成功のたびにゲームクロックを止める。',
    answer: false,
    explanation:
      '「第4Q・OT残り2:00以下でゴール後にクロックを止める」のは一般ルールで、U12には適用されない。U12ではゴール後もクロックは流れ続ける（審判が中断した場合を除く）。',
    refs: ['U12適用規則（規定しない項目）', 'knowledge/04-minibasket-diff'],
    ruleYear: 2026,
  },
  {
    id: 'tc-010',
    domain: 'to-clock',
    roles: ['timer'],
    ruleset: 'both',
    difficulty: 3,
    type: 'single',
    prompt:
      '白チームがタイムアウトを請求して待っている。相手の赤チームがフィールドゴールで得点した。タイマーはどうする？',
    choices: [
      '何もしない（クロックは流れたまま）',
      '速やかにゲームクロックを止め、ブザーを鳴らす',
      '審判が笛を鳴らすまで待つ',
    ],
    answer: 1,
    explanation:
      'タイムアウトを請求しているチームの相手がフィールドゴールで得点したときは、タイマーが速やかにクロックを止めてブザーを鳴らす場面。得点されたチームだけがタイムアウトを取れるタイミングであり、クルーで「入ったら白のタイムアウト」と事前共有しておくのが実務のコツ。',
    refs: ['JBA TOマニュアル 第6章', 'knowledge/09-to-timer-shotclock'],
    ruleYear: 2026,
  },
  {
    id: 'tc-011',
    domain: 'to-clock',
    roles: ['timer'],
    ruleset: 'both',
    difficulty: 2,
    type: 'truefalse',
    prompt:
      'ショットクロックのブザーが鳴ったら、タイマーは審判の笛を待たずにすぐゲームクロックを止める。',
    answer: false,
    explanation:
      'ショットクロックのブザー後にゲームクロックを止めるのは「審判が笛を鳴らしたとき」。相手チームが速やかに明らかなコントロールを得た場合、審判は笛を鳴らさずゲームは続く（ブザーは無視される）ので、笛がなければ止めない。',
    refs: ['JBA TOマニュアル 第6章', 'knowledge/09-to-timer-shotclock'],
    ruleYear: 2026,
  },
  {
    id: 'tc-012',
    domain: 'to-clock',
    roles: ['sc-operator'],
    ruleset: 'both',
    difficulty: 2,
    type: 'truefalse',
    prompt:
      'ディフェンスが片手でボールをタップした（はじいた）だけでも、コントロールが変わったのでショットクロックはリセットする。',
    answer: false,
    explanation:
      '触れただけ・はじいただけではコントロールは変わらない。ディフェンスが両手で保持または片手で保持したときに初めてコントロールが移り、24秒にリセットする。ショットクロックは「チームコントロール」とともに動くのが大原則。',
    refs: ['JBA TOマニュアル 第7章', 'knowledge/09-to-timer-shotclock'],
    ruleYear: 2026,
  },
  {
    id: 'tc-013',
    domain: 'to-clock',
    roles: ['sc-operator'],
    ruleset: 'both',
    difficulty: 1,
    type: 'single',
    prompt:
      'ショットがリングに当たって不成功。こぼれ球を攻撃していたチーム自身がリバウンドした。ショットクロックは？',
    choices: ['24秒にリセット', '14秒にリセット', '継続（リセットしない）'],
    answer: 1,
    explanation:
      'ボールがリングに触れて不成功となり、攻撃していたチームが再びコントロールしたときは14秒にリセットする（U12・一般共通）。相手チームがリバウンドしたときは24秒。',
    refs: ['U12適用規則 第29条', 'knowledge/09-to-timer-shotclock'],
    ruleYear: 2026,
  },
  {
    id: 'tc-014',
    domain: 'to-clock',
    roles: ['sc-operator'],
    ruleset: 'u12',
    difficulty: 2,
    type: 'single',
    prompt:
      'U12のゲーム。チームAの攻撃中（ショットクロック残り9秒）に、チームBがキックボールのバイオレーション。チームAのスローインで再開する。ショットクロックは？',
    choices: ['継続（9秒のまま）', '14秒にリセット', '24秒にリセット'],
    answer: 2,
    explanation:
      'U12にはフロントコート／バックコートの概念がないため、相手のファウル・バイオレーション後のスローインは常に24秒リセット。一般ならフロントコートで残り13秒以下→14秒だが、この規定はU12に存在しない。',
    refs: ['U12適用規則 第29条', 'knowledge/09-to-timer-shotclock'],
    ruleYear: 2026,
  },
  {
    id: 'tc-015',
    domain: 'to-clock',
    roles: ['sc-operator'],
    ruleset: 'both',
    difficulty: 3,
    type: 'single',
    prompt:
      '攻撃側チームにテクニカルファウルが宣せられ、相手にフリースロー1本が与えられた。FTの間、ショットクロックは？',
    choices: [
      '24秒にリセットする',
      '14秒にリセットする',
      '残り秒数を表示したまま継続（FT後は残りから再開）',
    ],
    answer: 2,
    explanation:
      'コントロールしているチーム側のテクニカルファウルでは、ショットクロックはリセットせず残り秒数のまま。罰則のFTが終わったら元の残り秒数から再開する。「FTがあれば必ず24にリセット」ではない点に注意。',
    refs: ['JBA TOマニュアル 第7章', 'knowledge/09-to-timer-shotclock'],
    ruleYear: 2026,
  },
  {
    id: 'tc-016',
    domain: 'to-clock',
    roles: ['sc-operator'],
    ruleset: 'both',
    difficulty: 3,
    type: 'single',
    prompt:
      'Q終了間際、ゲームクロックの残りが14秒未満になった。ここでショットクロックのリセット場面が生じたら、表示はどうする？',
    choices: [
      '24秒を表示してスタート',
      '14秒を表示してスタート',
      '競技時間の終了まで非表示のまま（消せない機材は24を表示して止めておく）',
    ],
    answer: 2,
    explanation:
      'ゲームクロック残りが14秒未満では、もうショットクロックのバイオレーションは起こり得ないため、リセット場面が生じても競技時間終了まで非表示のままにする。非表示にできない機材では24を表示しておく。',
    refs: ['JBA TOマニュアル 第7章', 'knowledge/09-to-timer-shotclock'],
    ruleYear: 2026,
  },
  {
    id: 'tc-017',
    domain: 'to-clock',
    roles: ['timer'],
    ruleset: 'both',
    difficulty: 1,
    type: 'single',
    prompt: 'ボールがライブの状態でゲームクロックをストップする基本の合図は？',
    choices: [
      '審判が笛を鳴らしたとき',
      'ボールがアウトオブバウンズになったのが見えたとき',
      'スコアラーがブザーを鳴らしたとき',
    ],
    answer: 0,
    explanation:
      '基本は「審判が笛を鳴らしたとき」に止める。笛が聞こえにくい会場では審判のシグナルを注視する。自分の判断で先に止めない。',
    refs: ['JBA TOマニュアル 第6章', 'knowledge/09-to-timer-shotclock'],
    ruleYear: 2026,
  },
  {
    id: 'tc-018',
    domain: 'to-clock',
    roles: ['timer'],
    ruleset: 'both',
    difficulty: 2,
    type: 'single',
    prompt: '国内の作法で、タイマーがクロックを「ストップ」したときのジェスチャーは？',
    choices: [
      '手を握って下ろす',
      '開いた手を頭上に上げる',
      '両手を交差する',
    ],
    answer: 1,
    explanation:
      'ストップと同時に「ストップ」とコールし、開いた手を頭上に上げる。スタートは逆に、開いて上げておいた手を握って下ろす。声出し＋ジェスチャー＋目視確認がクルーの相互チェックになる。',
    refs: ['JBA TOマニュアル 第6章', 'knowledge/09-to-timer-shotclock'],
    ruleYear: 2026,
  },
  {
    id: 'tc-019',
    domain: 'to-clock',
    roles: ['timer'],
    ruleset: 'both',
    difficulty: 3,
    type: 'single',
    prompt: 'フリースローが2本与えられた。タイマーが再開準備の手を上げるのはいつ？',
    choices: [
      '1本目の前',
      '最後の1投の前',
      '全部のFTが終わってから',
    ],
    answer: 1,
    explanation:
      'フリースローでは最後の1投の前に手を上げる（最後のFTが不成功ならボールがライブになり、クロックが動き出す可能性があるため）。',
    refs: ['JBA TOマニュアル 第6章', 'knowledge/09-to-timer-shotclock'],
    ruleYear: 2026,
  },
  {
    id: 'tc-020',
    domain: 'to-clock',
    roles: ['timer'],
    ruleset: 'both',
    difficulty: 2,
    type: 'truefalse',
    prompt: '各Q・OTの開始時、タイマーはコート上に5人ずついるかを確認してから再開準備の手を上げる。',
    answer: true,
    explanation:
      '各Q・OT開始時は両チーム5人ずつ揃っているかを確認してから手を上げる。人数の不足に最初に気づけるポジションでもある。',
    refs: ['JBA TOマニュアル 第6章', 'knowledge/09-to-timer-shotclock'],
    ruleYear: 2026,
  },
  {
    id: 'tc-021',
    domain: 'to-clock',
    roles: ['timer'],
    ruleset: 'both',
    difficulty: 2,
    type: 'single',
    prompt: 'タイマーが残り時間をクルーに定期コールするタイミングは？',
    choices: [
      '各Q残り5分と残り2分',
      '各Q残り3分と残り1分',
      '毎分',
    ],
    answer: 1,
    explanation:
      '各Qの残り3分と残り1分をクルーに知らせる。再開前には手を上げて残り時間をコール（例:3分12秒→「さんいちに」）し、手を上げたあとはベンチを見ない。',
    refs: ['JBA TOマニュアル 第6章', 'knowledge/09-to-timer-shotclock'],
    ruleYear: 2026,
  },
  {
    id: 'tc-022',
    domain: 'to-clock',
    roles: ['timer', 'sc-operator'],
    ruleset: 'both',
    difficulty: 3,
    type: 'single',
    prompt: 'タイマーの「14秒」コール（ショットクロックが14秒になったら伝える）の目的は？',
    choices: [
      '14秒リセットの操作をタイマーが代行するため',
      '誤リセット時や14秒リセット判断のとき、残りが既に14秒未満かを2人で確認できるようにするため',
      'ベンチに残り時間を知らせるため',
    ],
    answer: 1,
    explanation:
      '「14秒」コールはタイマーとSCオペレーターの相互チェック。14秒リセットすべき場面で残りが既に14秒未満だったか、誤操作がなかったかを2人で判断できるようにする。',
    refs: ['JBA TOマニュアル 第6章', 'knowledge/09-to-timer-shotclock'],
    ruleYear: 2026,
  },
  {
    id: 'tc-023',
    domain: 'to-clock',
    roles: ['timer', 'sc-operator'],
    ruleset: 'both',
    difficulty: 2,
    type: 'single',
    prompt: 'ショットクロック残り5秒からの声出しカウントダウン（「5、4、3…」）を担当するのは？',
    choices: ['ショットクロックオペレーター', 'タイマー', 'スコアラー'],
    answer: 1,
    explanation:
      'SC残り5秒からのカウントダウンはタイマーが担当する（SCオペレーターは操作に集中）。ただしQ終わりにゲームクロックとSCのカウントが重なるときは、タイマー＝ゲームクロック、SCオペレーター＝ショットクロックに分担する。',
    refs: ['JBA TOマニュアル 第6章', 'knowledge/09-to-timer-shotclock'],
    ruleYear: 2026,
  },
  {
    id: 'tc-024',
    domain: 'to-clock',
    roles: ['sc-operator'],
    ruleset: 'both',
    difficulty: 2,
    type: 'single',
    prompt: 'スローインで再開するとき、ショットクロックの計測を開始するのはいつ？',
    choices: [
      'スローインするプレーヤーがボールを持ったとき',
      'コート上のプレーヤーがボールに触れた瞬間',
      '審判が笛を鳴らしたとき',
    ],
    answer: 1,
    explanation:
      'スローインは、スローインするプレーヤーが持った時点でコントロール済みとみなされるため、コート上のプレーヤーが触れた瞬間に計測を開始する。ゲームクロックと同じ瞬間にスタートする。',
    refs: ['JBA TOマニュアル 第7章', 'knowledge/09-to-timer-shotclock'],
    ruleYear: 2026,
  },
  {
    id: 'tc-025',
    domain: 'to-clock',
    roles: ['sc-operator'],
    ruleset: 'both',
    difficulty: 2,
    type: 'single',
    prompt:
      '攻撃側のパスがディフェンスに最後に触れてアウトオブバウンズになり、引き続き攻撃側のスローインになった。ショットクロックは？',
    choices: [
      '24秒にリセット',
      '14秒にリセット',
      '止めるがリセットしない（残り秒数のまま）',
    ],
    answer: 2,
    explanation:
      'それまでコントロールしていたチームに引き続きスローインが与えられるときは、止めるがリセットしない。相手が最後に触れて出た場合も同じ。スローイン前に「継続8秒」のように残り秒数をクルーに知らせる。',
    refs: ['JBA TOマニュアル 第7章', 'knowledge/09-to-timer-shotclock'],
    ruleYear: 2026,
  },
  {
    id: 'tc-026',
    domain: 'to-clock',
    roles: ['sc-operator'],
    ruleset: 'both',
    difficulty: 3,
    type: 'single',
    prompt: 'ジャンプボールシチュエーション（ヘルドボール等）でそれまでコントロールしていたチームにAPスローインが与えられる。ショットクロックは？',
    choices: [
      '24秒にリセット',
      '止めるがリセットしない（残り秒数のまま）',
      '14秒にリセット',
    ],
    answer: 1,
    explanation:
      'ジャンプボールシチュエーション・ダブルファウル・罰則の相殺で、それまでコントロールしていたチームのスローインになるときは継続（リセットしない）。逆に相手側にボールが出るなら24秒。',
    refs: ['JBA TOマニュアル 第7章', 'knowledge/09-to-timer-shotclock'],
    ruleYear: 2026,
  },
  {
    id: 'tc-027',
    domain: 'to-clock',
    roles: ['sc-operator'],
    ruleset: 'both',
    difficulty: 1,
    type: 'single',
    prompt: 'ディフェンスがスティールに成功し、そのままドリブルで攻め始めた。ショットクロックの操作は？',
    choices: [
      '次のボールデッドで24秒にリセット',
      '直ちに24秒にリセットして、そのままスタート',
      '14秒にリセットしてスタート',
    ],
    answer: 1,
    explanation:
      '新たなチームがコントロールを得たとき（スティール等）は、ゲームが止まらないので即座に24秒リセット＋スタートする。リセット操作が最も忙しい場面のひとつ。',
    refs: ['JBA TOマニュアル 第7章', 'knowledge/09-to-timer-shotclock'],
    ruleYear: 2026,
  },
  {
    id: 'tc-028',
    domain: 'to-clock',
    roles: ['sc-operator'],
    ruleset: 'both',
    difficulty: 3,
    type: 'single',
    prompt: 'ボールがリングとバックボードの間に挟まり、ジャンプボールシチュエーションに。APアローで攻撃していた側にボールが与えられる場合、ショットクロックは？',
    choices: ['24秒にリセット', '14秒にリセット', '継続（リセットしない）'],
    answer: 1,
    explanation:
      'ボールがリングに挟まったJBSで攻撃側にボールが与えられるときは14秒にリセット（U12でも適用される数少ない14秒リセットのひとつ）。守備側に与えられるなら24秒。',
    refs: ['JBA TOマニュアル 第7章', 'knowledge/09-to-timer-shotclock'],
    ruleYear: 2026,
  },
  {
    id: 'tc-029',
    domain: 'to-clock',
    roles: ['sc-operator'],
    ruleset: 'both',
    difficulty: 2,
    type: 'single',
    prompt: '「リセットか継続か」でタイマーと見解が割れた。審判のジェスチャーもない。誰が判断する？',
    choices: [
      'タイマー',
      'ショットクロックオペレーター',
      'スコアラー',
      '多数決',
    ],
    answer: 1,
    explanation:
      'まず審判のリセットシグナル（人差し指を回す）を確認し、なければショットクロックオペレーターが判断する。リセット前に残り秒数を覚えておけば、誤ったときに戻せる根拠になる。',
    refs: ['JBA TOマニュアル 第7章', 'knowledge/09-to-timer-shotclock'],
    ruleYear: 2026,
  },
  {
    id: 'tc-030',
    domain: 'to-clock',
    roles: ['sc-operator', 'to-supporter'],
    ruleset: 'u12',
    difficulty: 2,
    type: 'single',
    prompt: 'デジタルのショットクロック表示がないU12の会場での小旗運用。旗の色の使い分けは？',
    choices: [
      '残り10〜5秒は赤、残り5〜0秒は黄色',
      '残り10〜5秒は黄色、残り5〜0秒は赤',
      '残り24〜10秒は黄色、残り10〜0秒は赤',
    ],
    answer: 1,
    explanation:
      '小旗運用では残り10〜5秒を黄色、残り5〜0秒を赤色の旗で表示する。機材がない会場でのSCオペレーターの代替手段。',
    refs: ['U12 TOハンドブック', 'knowledge/09-to-timer-shotclock'],
    ruleYear: 2026,
  },
  {
    id: 'tc-031',
    domain: 'to-clock',
    roles: ['timer'],
    ruleset: 'general',
    difficulty: 3,
    type: 'single',
    prompt: '一般のゲームで、第4Q残り2分10秒からタイマーが行う声出しは？',
    choices: [
      '「10、9…0」とカウントし、L2M（最後の2分）に入ることを全員で共有する',
      '「残り2分」と一度だけコールする',
      '特に何もしない（ブザーのみ）',
    ],
    answer: 0,
    explanation:
      '一般では第4Q・OTの残り2分10秒から「10、9…0」とカウントダウンし、L2Mに入ったことをクルー全員で共有する（ゴール後のクロック停止などL2M特有のルールに備える）。U12にはL2M規定がないためこの運用もない。',
    refs: ['JBA TOマニュアル 第6章', 'knowledge/09-to-timer-shotclock'],
    ruleYear: 2026,
  },
  {
    id: 'tc-032',
    domain: 'to-clock',
    roles: ['sc-operator'],
    ruleset: 'general',
    difficulty: 3,
    type: 'single',
    prompt:
      '一般のゲーム。攻撃側がフロントコートからスローインする場面で、ショットクロックの残りが14秒以上あった。どうする？',
    choices: [
      '14秒にリセット',
      '24秒にリセット',
      '継続（残り秒数のまま）',
    ],
    answer: 2,
    explanation:
      '一般ではフロントコートのスローインで残り14秒以上なら継続、13秒以下なら14秒にリセット。U12にはフロントコートの概念がないためこの使い分け自体がない（常に24秒か継続）。',
    refs: ['JBA TOマニュアル 第7章', 'knowledge/09-to-timer-shotclock'],
    ruleYear: 2026,
  },
]
