import type { Question } from '../types'

/** スコアシート記入（スコアラー・Aスコアラー） */
export const toScoresheetQuestions: Question[] = [
  {
    id: 'ss-001',
    domain: 'to-scoresheet',
    roles: ['scorer'],
    ruleset: 'both',
    difficulty: 1,
    type: 'single',
    prompt: 'スコアシートで赤ペンを使うのはどのクォーター？',
    choices: ['第1Q・第2Q', '第1Q・第3Q', '第2Q・第4Q', '全クォーター共通'],
    answer: 1,
    explanation:
      '第1Q・第3Qのランニングスコア・ファウル・タイムアウト・チームファウルは赤ペン。第2Q・第4Q・OTは濃色（青/黒）。スターターの×を囲む○も赤。',
    refs: ['JBA TOマニュアル 第4・5章', 'knowledge/08-to-scoresheet'],
    ruleYear: 2026,
  },
  {
    id: 'ss-002',
    domain: 'to-scoresheet',
    roles: ['scorer'],
    ruleset: 'both',
    difficulty: 2,
    type: 'single',
    prompt: 'オーバータイム（OT）の記録に使うペンの色は？',
    choices: ['赤', '濃色（青/黒）', 'どちらでもよい'],
    answer: 1,
    explanation:
      'OTは「第4Qに起こったもの」とみなすため濃色で記録する。同じ理由で、OTのチームファウルは第4Qに続けて数える。',
    refs: ['JBA TOマニュアル 第5章', 'knowledge/08-to-scoresheet'],
    ruleYear: 2026,
  },
  {
    id: 'ss-003',
    domain: 'to-scoresheet',
    roles: ['scorer'],
    ruleset: 'both',
    difficulty: 1,
    type: 'single',
    prompt: 'フリースロー成功（1点）のランニングスコアへの記入方法は？',
    choices: [
      '数字に斜線＋隣にプレーヤー番号',
      '数字に塗りつぶした丸●＋隣にプレーヤー番号',
      '数字を○で囲む＋隣にプレーヤー番号',
    ],
    answer: 1,
    explanation:
      'フリースローは数字を塗りつぶした丸●で消し、隣にプレーヤー番号を書く。フィールドゴール（2点）は斜線／。',
    refs: ['JBA TOマニュアル 第5章', 'knowledge/08-to-scoresheet'],
    ruleYear: 2026,
  },
  {
    id: 'ss-004',
    domain: 'to-scoresheet',
    roles: ['scorer'],
    ruleset: 'u12',
    difficulty: 2,
    type: 'single',
    prompt:
      'U12のゲームで赤チームのプレーヤーが誤って自チームのバスケットにシュートを入れてしまった（オウンゴール）。どう記録する？',
    choices: [
      '赤チームの得点として、そのプレーヤーの番号を記入',
      '白チームの得点として、白のキャプテンの番号を記入',
      '白チームの得点として、番号の代わりに▲を記入',
    ],
    answer: 2,
    explanation:
      'U12専用スコアシートではオウンゴールは相手チームの得点とし、番号の代わりに▲を記入する。一般ルールでは「相手チームのそのときコート上にいるキャプテン」の得点として番号を書く点が異なる。',
    refs: ['U12適用規則', 'knowledge/08-to-scoresheet'],
    ruleYear: 2026,
  },
  {
    id: 'ss-005',
    domain: 'to-scoresheet',
    roles: ['scorer'],
    ruleset: 'general',
    difficulty: 2,
    type: 'single',
    prompt: '3点シュート成功（3P採用大会）のランニングスコアへの記入方法は？',
    choices: [
      '数字に斜線＋番号を○で囲む',
      '数字を▲で消す＋番号',
      '数字に斜線を2本＋番号',
    ],
    answer: 0,
    explanation:
      '3点は数字に斜線を引き、プレーヤー番号を○で囲む。なお2点か3点かはスコアラーがラインを見て判断するのではなく、審判のシグナルで判断する。U12の通常大会に3Pはない。',
    refs: ['JBA TOマニュアル 第5章', 'knowledge/08-to-scoresheet'],
    ruleYear: 2026,
  },
  {
    id: 'ss-006',
    domain: 'to-scoresheet',
    roles: ['scorer'],
    ruleset: 'both',
    difficulty: 2,
    type: 'single',
    prompt: 'スターターの×印を赤ペンの○で囲むのは、誰が・いつ行う？',
    choices: [
      'HCがサインするとき',
      'スコアラーが、ゲーム開始時にコート上の5人を確認してから',
      'Aスコアラーが、開始10分前に',
    ],
    answer: 1,
    explanation:
      '開始10分前までにHCがスターター5人に×を付けてサインし、ゲーム開始時にスコアラーがコート上の5人と照合してから×を赤○で囲む。相違があれば速やかに審判へ知らせる。',
    refs: ['JBA TOマニュアル 第4章', 'knowledge/08-to-scoresheet'],
    ruleYear: 2026,
  },
  {
    id: 'ss-007',
    domain: 'to-scoresheet',
    roles: ['scorer'],
    ruleset: 'u12',
    difficulty: 2,
    type: 'single',
    prompt: 'U12スコアシートの出場時限欄。Qの最初から出場するプレーヤーと途中出場の記入は？',
    choices: [
      '最初から＝×、途中＝○',
      '最初から＝／、途中＝＼',
      '最初から＝○、途中＝×',
    ],
    answer: 1,
    explanation:
      'U12は各Q開始前にメンバーチェックし、出場するプレーヤーに／を記入。途中出場は＼。出場義務ルール（1Q以上2Q以下など）のチェックに直結するため正確に付ける。HCのサインは不要。',
    refs: ['U12 TOハンドブック', 'knowledge/08-to-scoresheet'],
    ruleYear: 2026,
  },
  {
    id: 'ss-008',
    domain: 'to-scoresheet',
    roles: ['scorer'],
    ruleset: 'both',
    difficulty: 1,
    type: 'single',
    prompt:
      '第3Qに白4番がアンスポーツマンライクファウルを宣せられ、相手にフリースロー2本。スコアシートには何色でどう記入する？',
    choices: ['濃色で「U₂」', '赤で「U₂」', '赤で「P₂」', '赤で「U」とだけ'],
    answer: 1,
    explanation:
      '第3Qは赤ペン。アンスポはU、フリースローが与えられるときは記号の右下に本数を小さく添えるのでU₂。同じプレーヤーに2個目のU（またはT+U）が付いたらすぐ隣にGDを記入し、速やかに審判に知らせる。',
    refs: ['JBA TOマニュアル 第5章', 'knowledge/08-to-scoresheet'],
    ruleYear: 2026,
  },
  {
    id: 'ss-009',
    domain: 'to-scoresheet',
    roles: ['scorer', 'a-scorer'],
    ruleset: 'both',
    difficulty: 2,
    type: 'truefalse',
    prompt: 'HCに記録されるファウル（C・B・M）もチームファウルに数える。',
    answer: false,
    explanation:
      'HCに記録されるC・B・Mはチームファウルに数えない。チームファウル欄の×はプレーヤーのファウル（P/T/U/D）が記録されたときに付ける。',
    refs: ['JBA TOマニュアル 第5章', 'knowledge/08-to-scoresheet'],
    ruleYear: 2026,
  },
  {
    id: 'ss-010',
    domain: 'to-scoresheet',
    roles: ['scorer'],
    ruleset: 'both',
    difficulty: 2,
    type: 'single',
    prompt: 'プレーヤーが失格・退場（GD）になるファウルの組み合わせは？',
    choices: [
      'T2個／U2個／T+U のいずれか',
      'T3個のみ',
      'U2個のみ',
      'P5個＋T1個',
    ],
    answer: 0,
    explanation:
      'プレーヤーはテクニカル2個・アンスポ2個・T+Uの組み合わせで失格（GD）。該当ファウルのすぐ隣の枠にGDと記入し、速やかに審判に知らせる。5個目のファウルの通知と並ぶスコアラーの重要任務。',
    refs: ['JBA TOマニュアル 第5章', 'knowledge/08-to-scoresheet'],
    ruleYear: 2026,
  },
  {
    id: 'ss-011',
    domain: 'to-scoresheet',
    roles: ['scorer'],
    ruleset: 'u12',
    difficulty: 3,
    type: 'single',
    prompt: 'U12でHCが失格・退場（GD）になるMファウル（マンツーマンペナルティ）の個数は？',
    choices: ['2個', '3個', '4個', 'Mでは失格にならない'],
    answer: 1,
    explanation:
      'U12ではM3個でHCが失格（U15はM2個）。MはマンツーマンペナルティでHCに記録され、チームファウルには数えない。ほかにHCはC2個／B3個／2B+1Cでも失格。',
    refs: ['JBA TOマニュアル 第5章', 'knowledge/08-to-scoresheet'],
    ruleYear: 2026,
  },
  {
    id: 'ss-012',
    domain: 'to-scoresheet',
    roles: ['scorer'],
    ruleset: 'u12',
    difficulty: 3,
    type: 'single',
    prompt:
      'U12（6分クォーター）で、残り2分35秒にタイムアウトが認められた。タイムアウト欄に記入する数字は？',
    choices: ['2', '3', '4', '6'],
    answer: 2,
    explanation:
      'タイムアウト欄には「認められたときの各Qの経過時間（分）」を切り上げで記入する。6分−2分35秒＝3分25秒経過→切り上げて「4」。',
    refs: ['JBA TOマニュアル 第5章', 'knowledge/08-to-scoresheet'],
    ruleYear: 2026,
  },
  {
    id: 'ss-013',
    domain: 'to-scoresheet',
    roles: ['scorer'],
    ruleset: 'both',
    difficulty: 3,
    type: 'truefalse',
    prompt: 'APスローインの最中にファウルがあったら、APアローを反転させる。',
    answer: false,
    explanation:
      'APスローインの前・最中にファウルがあってもアローは反転しない（スローインの権利は取り消されない）。反転するのは「APスローインが終わったとき」（ボールがコート上のプレーヤーに正当に触れた／スローインチームのバイオレーション）と前半終了時。',
    refs: ['JBA TOマニュアル 第4章', 'knowledge/08-to-scoresheet'],
    ruleYear: 2026,
  },
  {
    id: 'ss-014',
    domain: 'to-scoresheet',
    roles: ['scorer'],
    ruleset: 'both',
    difficulty: 2,
    type: 'truefalse',
    prompt: '前半が終了したら、APアローは速やかに反転させる。',
    answer: true,
    explanation:
      '後半は攻撃方向が入れ替わるため、前半終了時にアローを速やかに反転し、審判・両チームと共有する。ジャンプボールシチュエーションが宣せられたらアローに手を添えて反転の準備をする習慣も大事。',
    refs: ['JBA TOマニュアル 第4章', 'knowledge/08-to-scoresheet'],
    ruleYear: 2026,
  },
  {
    id: 'ss-015',
    domain: 'to-scoresheet',
    roles: ['scorer', 'a-scorer'],
    ruleset: 'both',
    difficulty: 2,
    type: 'single',
    prompt: 'スコアシートの記録の誤りは、いつまで訂正できる？',
    choices: [
      'ゲーム終了のブザーが鳴るまで',
      'クルーチーフがスコアシートにサインするまで',
      'チームが会場を出るまで',
      '大会主催者に報告すればいつでも',
    ],
    answer: 1,
    explanation:
      'ゲーム終了の合図の後でも、クルーチーフがサインする前なら訂正する（結果に影響しても訂正しなければならない）。サイン後は訂正できず、大会主催者への報告のみになる。',
    refs: ['JBA TOマニュアル 4.5.2', 'knowledge/08-to-scoresheet'],
    ruleYear: 2026,
  },
  {
    id: 'ss-016',
    domain: 'to-scoresheet',
    roles: ['a-scorer'],
    ruleset: 'both',
    difficulty: 2,
    type: 'single',
    prompt: 'プレーヤーファウルの個数標識の出し方（国内の分担）は？',
    choices: [
      '正面に1回だけ掲げる',
      '①ベンチ→②正面→③再びベンチ の3段階で表示する',
      '両ベンチに同時に見せる',
    ],
    answer: 1,
    explanation:
      'スコアラーのコール後、Aスコアラーが標識を①ファウルしたプレーヤーのベンチ→②正面→③再びベンチの3段階で表示する。5個目はブザー（スコアラー）＋2段階表示。',
    refs: ['JBA TOマニュアル（国内分担）', 'knowledge/08-to-scoresheet'],
    ruleYear: 2026,
  },
  {
    id: 'ss-017',
    domain: 'to-scoresheet',
    roles: ['a-scorer'],
    ruleset: 'both',
    difficulty: 2,
    type: 'single',
    prompt: '4個目のチームファウルが宣せられた。チームファウルペナルティの赤色標識はいつ表示する？',
    choices: [
      '4個目が記録されたらすぐ',
      'ボールがライブになってから',
      '5個目が記録されてから',
      '次のクォーターの最初から',
    ],
    answer: 1,
    explanation:
      '4個目のチームファウルの後、ボールがライブになってから赤色標識を表示する（数字の標識は消す）。以降そのQはファウルごとに相手にFTが与えられるボーナス状態。',
    refs: ['JBA TOマニュアル 第5章', 'knowledge/08-to-scoresheet'],
    ruleYear: 2026,
  },
  {
    id: 'ss-018',
    domain: 'to-scoresheet',
    roles: ['scorer', 'a-scorer'],
    ruleset: 'both',
    difficulty: 1,
    type: 'single',
    prompt: '毎クォーター終了時にスコアラーがやるべき照合は？',
    choices: [
      'ランニングスコア・ファウル数・タイムアウト数をスコアボードと照合する',
      '両チームのHCにサインをもらう',
      'スコアシートを審判に提出する',
    ],
    answer: 0,
    explanation:
      '各Q終了時にランニングスコア・ファウル数・タイムアウト数をスコアボードと照合する。食い違いの早期発見が訂正の手間を減らす。得点のたびのコール交換（「23点目」⇔「19対23」）も予防策。',
    refs: ['JBA TOマニュアル 第5章', 'knowledge/08-to-scoresheet'],
    ruleYear: 2026,
  },
  {
    id: 'ss-019',
    domain: 'to-scoresheet',
    roles: ['scorer'],
    ruleset: 'both',
    difficulty: 1,
    type: 'single',
    prompt: 'ゲーム開始前、メンバーリストの氏名はどの順で記入する？',
    choices: [
      '提出されたリストの記載順',
      'ユニフォーム番号順',
      'スターターが先、交代要員が後',
    ],
    answer: 1,
    explanation:
      'チームリストをもとにユニフォーム番号順に記入する。先に記載されたチーム（ホーム）がチームA＝上の枠。使わなかった行は横線＋斜線で消す（HCのサイン後に引く）。',
    refs: ['JBA TOマニュアル 第4章', 'knowledge/08-to-scoresheet'],
    ruleYear: 2026,
  },
  {
    id: 'ss-020',
    domain: 'to-scoresheet',
    roles: ['scorer'],
    ruleset: 'general',
    difficulty: 2,
    type: 'single',
    prompt: '交代要員が初めてゲームに出場した。Player in欄への記入は？',
    choices: [
      '×を記入し、○で囲む',
      '×を記入する（○では囲まない。そのQの色で）',
      '／を記入する',
    ],
    answer: 1,
    explanation:
      '交代要員の初出場はPlayer in欄に×のみ（○で囲むのはスターターだけ）。記入色はそのQの色。U12は出場時限欄（／と＼）を使う別方式。',
    refs: ['JBA TOマニュアル 第4章', 'knowledge/08-to-scoresheet'],
    ruleYear: 2026,
  },
  {
    id: 'ss-021',
    domain: 'to-scoresheet',
    roles: ['scorer'],
    ruleset: 'both',
    difficulty: 2,
    type: 'single',
    prompt: '各クォーター終了時のランニングスコアの締め方は？',
    choices: [
      '最後の得点を太い○で囲み、得点と番号のすぐ下に太い横線1本',
      '最後の得点の下に横線2本',
      '未使用の列をすべて斜線で消す',
    ],
    answer: 0,
    explanation:
      'Q終わりはそのQのペンで最後の得点を太い○で囲み、すぐ下に太い横線1本を引き、下段「スコア」欄にそのQの得点を記入する。横線2本と未使用列の斜線はゲーム終了時。',
    refs: ['JBA TOマニュアル 第5章', 'knowledge/08-to-scoresheet'],
    ruleYear: 2026,
  },
  {
    id: 'ss-022',
    domain: 'to-scoresheet',
    roles: ['scorer'],
    ruleset: 'both',
    difficulty: 2,
    type: 'single',
    prompt: 'ゲーム終了時の締めで記入するものに含まれないのは？',
    choices: [
      '最終スコアと勝者チーム名',
      'ゲーム終了時刻',
      '観客数',
    ],
    answer: 2,
    explanation:
      'ゲーム終了時は最後の得点を○で囲み太い横線2本、未使用のランニングスコア列に斜線（濃色）、最終スコア・勝者チーム名・終了時刻を記入する。観客数は記録しない。',
    refs: ['JBA TOマニュアル 第5章', 'knowledge/08-to-scoresheet'],
    ruleYear: 2026,
  },
  {
    id: 'ss-023',
    domain: 'to-scoresheet',
    roles: ['scorer'],
    ruleset: 'both',
    difficulty: 3,
    type: 'single',
    prompt: '第1Qと第2Qの間のインターバル中にテクニカルファウルが宣せられた。何色で記録する？',
    choices: [
      '赤（第1Qの色）',
      '濃色（第2Qの色）',
      'どちらでもよい',
    ],
    answer: 1,
    explanation:
      'プレーのインターバル中のファウルは次のQの色で記録する。Q1-Q2間なら第2Qの色＝濃色。',
    refs: ['JBA TOマニュアル 第5章', 'knowledge/08-to-scoresheet'],
    ruleYear: 2026,
  },
  {
    id: 'ss-024',
    domain: 'to-scoresheet',
    roles: ['scorer'],
    ruleset: 'both',
    difficulty: 3,
    type: 'single',
    prompt: 'ダブルファウルなどで罰則が相殺されたファウル（第42条）の記録方法は？',
    choices: [
      '記号の右下にFT本数の代わりに0を書く',
      '記号の後ろに小さいcを書く',
      '記録しない',
    ],
    answer: 1,
    explanation:
      '罰則が相殺されたファウルは記号の後ろに小さいc（cancelled）を添える（例: Pc）。ファウル自体は記録され、プレーヤーのファウル数・チームファウルには通常どおり数える。',
    refs: ['JBA TOマニュアル 第5章', 'knowledge/08-to-scoresheet'],
    ruleYear: 2026,
  },
  {
    id: 'ss-025',
    domain: 'to-scoresheet',
    roles: ['scorer'],
    ruleset: 'general',
    difficulty: 3,
    type: 'truefalse',
    prompt:
      '第4Q最後の2分のスローイン中、ディフェンスのファウル（スローインファウル）はP₁と記録し、チームファウルにも数える。',
    answer: true,
    explanation:
      'スローインファウル（第4Q・OT最後の2分のスローイン中のディフェンスファウル）はP₁と記録し、チームファウルに数える。HCのファウル（C・B・M）がチームファウルに数えないのとは対照的。',
    refs: ['JBA TOマニュアル 第5章', 'knowledge/08-to-scoresheet'],
    ruleYear: 2026,
  },
  {
    id: 'ss-026',
    domain: 'to-scoresheet',
    roles: ['scorer'],
    ruleset: 'both',
    difficulty: 3,
    type: 'single',
    prompt: '5ファウル退場済みのプレーヤー（交代要員扱い）がテクニカルファウルを宣せられた。記録は？',
    choices: [
      '本人の欄にT',
      'HCの枠にB',
      'キャプテンの欄にT',
    ],
    answer: 1,
    explanation:
      '交代要員・5ファウル済みメンバー・チーム関係者のT／DQはHCの枠にBとして記録する（DQなら本人にはDも記録）。このBはチームファウルに数えない。',
    refs: ['JBA TOマニュアル 第5章', 'knowledge/08-to-scoresheet'],
    ruleYear: 2026,
  },
  {
    id: 'ss-027',
    domain: 'to-scoresheet',
    roles: ['scorer', 'a-scorer'],
    ruleset: 'both',
    difficulty: 2,
    type: 'single',
    prompt: 'ファウルを記録するたびにスコアラーが声に出す内容の型は？',
    choices: [
      '「白14番、ファウル」とだけ言う',
      '「白14番、個人4個目、チーム3個目」のように個人とチームの数を共有する',
      '数字は言わずAスコアラーに標識で伝える',
    ],
    answer: 1,
    explanation:
      '「白14番、個人4個目、チーム3個目」のように声に出してクルーと共有する（伝えるチームファウル数は5個まで）。5個目・失格の見逃し防止と表示の正確さにつながる。',
    refs: ['JBA TOマニュアル 第5章', 'knowledge/08-to-scoresheet'],
    ruleYear: 2026,
  },
  {
    id: 'ss-028',
    domain: 'to-scoresheet',
    roles: ['a-scorer'],
    ruleset: 'both',
    difficulty: 2,
    type: 'single',
    prompt: 'ファウルが宣せられたとき、チームファウルの表示と個人ファウルの標識、どちらを先に出す？',
    choices: [
      '個人ファウルの標識が先',
      'チームファウルの表示が先（審判のレポートで確認したら）',
      '同時に出す',
    ],
    answer: 1,
    explanation:
      '審判のレポートで確認したらチームファウルを個人ファウルより先に表示する。積み上げ式器具の場合、チームA側はショットクロックオペレーターが担当する分担もある。',
    refs: ['JBA TOマニュアル（国内分担）', 'knowledge/08-to-scoresheet'],
    ruleYear: 2026,
  },
  {
    id: 'ss-029',
    domain: 'to-scoresheet',
    roles: ['a-scorer', 'timer'],
    ruleset: 'both',
    difficulty: 3,
    type: 'single',
    prompt: '得点入力とゲームクロックが一体になった機材の場合、得点入力は誰が行う？',
    choices: [
      'アシスタントスコアラー',
      'タイマー（クロック操作優先。得点コールはAスコアラー）',
      'スコアラー',
    ],
    answer: 1,
    explanation:
      '一体型機材ではタイマーが得点入力を行う（その場合もクロック操作が最優先）。得点のコール自体はAスコアラーが担当し続ける。会場の機材によって分担が変わる例。',
    refs: ['JBA TOマニュアル（国内分担）', 'knowledge/08-to-scoresheet'],
    ruleYear: 2026,
  },
  {
    id: 'ss-030',
    domain: 'to-scoresheet',
    roles: ['scorer'],
    ruleset: 'both',
    difficulty: 2,
    type: 'single',
    prompt: '国内大会でのスコアシートの訂正方法として正しいのは？',
    choices: [
      '修正テープで消して書き直す',
      '間違いを二本の横線で消し、周囲の余白に正しい記録を書く',
      '間違いを塗りつぶして上から書く',
    ],
    answer: 1,
    explanation:
      '間違いは二本の横線で消して余白に正しく記録する。修正テープ・修正液は不可。国内はクルーチーフの小さなサインは省略できる。すぐ直せないときは付箋を貼ってタイムアウトやインターバルで訂正する。',
    refs: ['JBA TOマニュアル 4.5.2', 'knowledge/08-to-scoresheet'],
    ruleYear: 2026,
  },
  {
    id: 'ss-031',
    domain: 'to-scoresheet',
    roles: ['scorer'],
    ruleset: 'both',
    difficulty: 3,
    type: 'single',
    prompt: '得点を誤って多く記録して（または誤ったチームに記録して）しまった場合の訂正方法は？',
    choices: [
      '誤った得点を横線で消して書き直す',
      '消さずに正しい得点から記録を再開し、誤った得点の横に小さい点（・）を付けて目印にする',
      'スコアシートを新しく書き直す',
    ],
    answer: 1,
    explanation:
      '多く記録・誤チームへの記録は消さず、正しい得点から再開して誤りの横に小さい点（・）を付ける。逆に「少なく記録」（2点と書いたが3点だった）は横線で消して正しく記録する。ケースで訂正方法が違う点に注意。',
    refs: ['JBA TOマニュアル 4.5.2', 'knowledge/08-to-scoresheet'],
    ruleYear: 2026,
  },
  {
    id: 'ss-032',
    domain: 'to-scoresheet',
    roles: ['scorer', 'a-scorer'],
    ruleset: 'both',
    difficulty: 2,
    type: 'single',
    prompt: 'ショットが決まったときのスコアラーの手順の習慣として正しい順番は？',
    choices: [
      '記入 → ベンチ確認 → ライブ確認',
      'ベンチ確認（タイムアウト請求）→ ライブ確認 → 記入',
      'ライブ確認 → 記入 → ベンチ確認',
    ],
    answer: 1,
    explanation:
      'ゴール後はまずベンチを見てタイムアウト請求がないか確認し、ボールがライブになるのを確認してから記入する。先に下を向いて書いてしまうと、得点後の請求（得点されたチームのみ可）を見逃す。',
    refs: ['U12 TOハンドブック', 'knowledge/08-to-scoresheet'],
    ruleYear: 2026,
  },
  {
    id: 'ss-033',
    domain: 'to-scoresheet',
    roles: ['a-scorer'],
    ruleset: 'both',
    difficulty: 2,
    type: 'single',
    prompt: 'U12ハンドブックの声出しの型で、Aスコアラーが得点をコールするときの順番は？',
    choices: [
      '得点したチームが先（例:「23対19」）',
      '常にA対Bの順（例:「19対23」）',
      '負けているチームが先',
    ],
    answer: 1,
    explanation:
      'Aスコアラーのスコアコールは常にA対Bの順（例:「赤4番。19対23」）。順番を固定することで聞き間違いを防ぐ。スコアラーの「23点目」とのコール交換が食い違いの早期発見になる。',
    refs: ['U12 TOハンドブック', 'knowledge/08-to-scoresheet'],
    ruleYear: 2026,
  },
  {
    id: 'ss-034',
    domain: 'to-scoresheet',
    roles: ['scorer'],
    ruleset: 'general',
    difficulty: 2,
    type: 'single',
    prompt: '一般ルールのタイムアウトの回数は？',
    choices: [
      '各Q1回・OT各1回',
      '前半2回・後半3回（第4Q残り2:00以下では2回まで）・OT各1回',
      '前半3回・後半2回・OT各1回',
    ],
    answer: 1,
    explanation:
      '一般は前半2回・後半3回（ただし第4Q残り2:00以下では2回まで）・OT各1回。U12は各Q・各OTに1回ずつ。未使用の枠は各ハーフ（U12は各Q）の終わりに2本線で消す。',
    refs: ['JBA TOマニュアル 第5章', 'knowledge/08-to-scoresheet'],
    ruleYear: 2026,
  },
  {
    id: 'ss-035',
    domain: 'to-scoresheet',
    roles: ['scorer'],
    ruleset: 'both',
    difficulty: 1,
    type: 'single',
    prompt: 'ゲーム開始のジャンプボール後、APアローはどうセットする？',
    choices: [
      'コントロールを得たチームの攻撃方向に向ける',
      'コントロールを得られなかったチームの攻撃方向に向ける',
      '前半はセットしない',
    ],
    answer: 1,
    explanation:
      '最初のジャンプボールでコントロールを得られなかったチームが次のAPスローインの権利を持つので、そのチームの攻撃方向（バスケット）にアローを向ける。',
    refs: ['JBA TOマニュアル 第4章', 'knowledge/08-to-scoresheet'],
    ruleYear: 2026,
  },
]
