import type { Question } from '../types'

/** U12（ミニバス）固有ルール（TO業務に関わるもの中心） */
export const u12DiffQuestions: Question[] = [
  {
    id: 'ud-001',
    domain: 'u12-diff',
    roles: ['timer'],
    ruleset: 'u12',
    difficulty: 1,
    type: 'single',
    prompt: 'U12の1ピリオド（クォーター）の長さは？',
    choices: ['5分', '6分', '8分', '10分'],
    answer: 1,
    explanation: 'U12は1ピリオド6分（一般は10分）。インターバル終了時にはゲームクロックを6:00にリセットする。',
    refs: ['U12適用規則 第8条', 'knowledge/04-minibasket-diff'],
    ruleYear: 2026,
  },
  {
    id: 'ud-002',
    domain: 'u12-diff',
    roles: ['timer'],
    ruleset: 'u12',
    difficulty: 2,
    type: 'single',
    prompt: 'U12のオーバータイム（OT）の長さは？',
    choices: ['2分', '3分', '5分'],
    answer: 1,
    explanation:
      'U12のOTは3分（一般は5分）。なおU12の同点は原則引き分けで、OTを行うかは大会規定による。OT間のインターバルは2分で、終了1分前にブザー。',
    refs: ['U12適用規則 第8条', 'knowledge/04-minibasket-diff'],
    ruleYear: 2026,
  },
  {
    id: 'ud-003',
    domain: 'u12-diff',
    roles: ['to-supporter'],
    ruleset: 'u12',
    difficulty: 1,
    type: 'single',
    prompt: 'U12（通常大会）のリングの高さとボールのサイズは？',
    choices: [
      '305cm・7号球',
      '260cm・5号球（または軽量5号）',
      '280cm・6号球',
    ],
    answer: 1,
    explanation:
      'U12はリング260cm・5号球（一般は305cm・7号球）。全国ミニバス大会のみ「305cm・6号球・3Pライン導入」の特別ルールがあるが、通常試合には適用されない。',
    refs: ['U12適用規則 第2・3条', 'knowledge/04-minibasket-diff'],
    ruleYear: 2026,
  },
  {
    id: 'ud-004',
    domain: 'u12-diff',
    roles: ['sc-operator', 'timer'],
    ruleset: 'u12',
    difficulty: 1,
    type: 'truefalse',
    prompt: 'U12にも8秒ルール（8秒以内にフロントコートへ運ぶ）がある。',
    answer: false,
    explanation:
      'U12にはフロントコート・バックコートの概念がないため、8秒ルールもバックコートバイオレーションも存在しない。ショットクロックは24秒のみで管理する。',
    refs: ['U12適用規則 第5章', 'knowledge/04-minibasket-diff'],
    ruleYear: 2026,
  },
  {
    id: 'ud-005',
    domain: 'u12-diff',
    roles: ['sc-operator'],
    ruleset: 'u12',
    difficulty: 2,
    type: 'single',
    prompt: 'U12で「規定しない（存在しない）」ものの組み合わせとして正しいのは？',
    choices: [
      '3秒ルール・8秒ルール・24秒ルール',
      'スリーポイントライン・ノーチャージセミサークル・スローインライン',
      'タイムアウト・交代・オーバータイム',
    ],
    answer: 1,
    explanation:
      'U12ではフロント/バックコート規定・3Pライン・ノーチャージセミサークル・スローインライン・L2Mのクロック停止・キャプテン規定を適用しない。3秒ルールと24秒（ショットクロック）はU12にもある。',
    refs: ['U12適用規則（規定しない項目）', 'knowledge/04-minibasket-diff'],
    ruleYear: 2026,
  },
  {
    id: 'ud-006',
    domain: 'u12-diff',
    roles: ['scorer'],
    ruleset: 'u12',
    difficulty: 1,
    type: 'single',
    prompt: 'U12のタイムアウトの回数は？',
    choices: [
      '前半2回・後半3回',
      '各クォーターに1回・各OTに1回',
      '各ハーフに2回',
    ],
    answer: 1,
    explanation:
      'U12は各Q・各OTに1回ずつ（一般は前半2回・後半3回・OT各1回）。未使用の枠は各Qの終わりに2本線で消す。',
    refs: ['U12適用規則 第18条', 'knowledge/04-minibasket-diff'],
    ruleYear: 2026,
  },
  {
    id: 'ud-007',
    domain: 'u12-diff',
    roles: ['scorer'],
    ruleset: 'u12',
    difficulty: 2,
    type: 'single',
    prompt: 'U12のQ1〜Q3で交代ができるのはいつ？',
    choices: [
      'ボールデッドのときならいつでも',
      'プレーのインターバル中とハーフタイム中のみ',
      'タイムアウト中のみ',
    ],
    answer: 1,
    explanation:
      'U12のQ1〜Q3はインターバル・ハーフタイム中のみ交代可。Q4とOTは一般と同じ「交代が認められる時機」（ボールデッド時など）。出場義務ルールと連動した仕組み。',
    refs: ['U12適用規則 第19条', 'knowledge/04-minibasket-diff'],
    ruleYear: 2026,
  },
  {
    id: 'ud-008',
    domain: 'u12-diff',
    roles: ['scorer'],
    ruleset: 'both',
    difficulty: 1,
    type: 'single',
    prompt: '交代をスコアラーズテーブルに申し出ることができるのは誰？',
    choices: ['HC（ヘッドコーチ）', 'A.コーチ', '交代要員のプレーヤー自身', 'キャプテン'],
    answer: 2,
    explanation:
      '交代の申し出は交代要員自身がテーブルへ行って行う（コーチは不可）。逆にタイムアウトの請求はHC・A.コーチのみ。対で覚える。',
    refs: ['競技規則 第19条', 'knowledge/04-minibasket-diff'],
    ruleYear: 2026,
  },
  {
    id: 'ud-009',
    domain: 'u12-diff',
    roles: ['to-supporter'],
    ruleset: 'u12',
    difficulty: 3,
    type: 'single',
    prompt: 'U12の出場義務ルール。10人以上でエントリーしたチームの各プレーヤーは？',
    choices: [
      '第3Qまでに1Q以上・2Q以下の出場',
      '第4Qまでに1Q以上の出場',
      '第3Qまでに2Q以上の出場',
      '全員が毎Q出場',
    ],
    answer: 0,
    explanation:
      '10人以上エントリーでは第3Qまでに各プレーヤーが1Q以上・2Q以下出場する義務がある（8〜9人全員エントリーは1Q以上）。満たせないとゲーム没収（20対0）になり得る重要ルール。出場時限欄の／＼記録がこのチェックの根拠になる。',
    refs: ['U12適用規則 第4条', 'knowledge/04-minibasket-diff'],
    ruleYear: 2026,
  },
  {
    id: 'ud-010',
    domain: 'u12-diff',
    roles: ['to-supporter'],
    ruleset: 'u12',
    difficulty: 2,
    type: 'truefalse',
    prompt: 'U12では、プレーヤーは第3Qまでに3クォーター連続で出場できない。',
    answer: true,
    explanation:
      '連続出場の禁止：第3Qまでに3Q連続出場は不可。出場義務（1Q以上2Q以下）とあわせて、出場時限欄で管理する。',
    refs: ['U12適用規則 第4条', 'knowledge/04-minibasket-diff'],
    ruleYear: 2026,
  },
  {
    id: 'ud-011',
    domain: 'u12-diff',
    roles: ['sc-operator', 'scorer'],
    ruleset: 'u12',
    difficulty: 3,
    type: 'single',
    prompt: 'U12でアンスポーツマンライクファウルのフリースロー後、ゲームはどこから再開する？',
    choices: [
      'スローインラインから',
      'スコアラーズテーブル反対側のセンターライン延長線上からのスローイン',
      'センターサークルのジャンプボール',
    ],
    answer: 1,
    explanation:
      'U12にはスローインラインがないため、アンスポ・DQの罰則後はテーブル反対側のセンターライン延長線上からスローイン。このときショットクロックは24秒（一般はスローインラインから14秒）。',
    refs: ['U12適用規則 第37・38条', 'knowledge/04-minibasket-diff'],
    ruleYear: 2026,
  },
  {
    id: 'ud-012',
    domain: 'u12-diff',
    roles: ['timer', 'scorer'],
    ruleset: 'u12',
    difficulty: 2,
    type: 'truefalse',
    prompt: 'U12のゲームが同点で終わった場合、原則としてオーバータイムを行う。',
    answer: false,
    explanation:
      'U12の同点は原則引き分け。大会規定によりOT（3分）を行う場合もある。一般はOT必須（決着がつくまで5分を繰り返す）。',
    refs: ['U12適用規則 第8条', 'knowledge/04-minibasket-diff'],
    ruleYear: 2026,
  },
  {
    id: 'ud-013',
    domain: 'u12-diff',
    roles: ['scorer'],
    ruleset: 'u12',
    difficulty: 2,
    type: 'single',
    prompt: 'アンダーカテゴリー（U12含む15歳以下）のディフェンス規定は？',
    choices: [
      'ゾーンディフェンス推奨',
      'マンツーマン推進（ゾーンディフェンス禁止）。違反はHCにMが記録される',
      '制限なし',
    ],
    answer: 1,
    explanation:
      '15歳以下はマンツーマン推進でゾーンディフェンスは禁止。ペナルティはHCへのM記録で、U12はM3個でHC失格。Mはチームファウルに数えない。',
    refs: ['U12適用規則 第4章', 'knowledge/04-minibasket-diff'],
    ruleYear: 2026,
  },
  {
    id: 'ud-014',
    domain: 'u12-diff',
    roles: ['scorer', 'to-supporter'],
    ruleset: 'u12',
    difficulty: 2,
    type: 'truefalse',
    prompt: 'U12にはキャプテンの規定がないので、スコアシートに（CAP)は記入しない。',
    answer: true,
    explanation:
      'U12はキャプテン規定を適用しないため（CAP）の記入もない。一般ではキャプテンの氏名の横に（CAP）を記入する。オウンゴールの扱いが違うのも同じ理由（一般は相手キャプテンの得点、U12は▲）。',
    refs: ['U12適用規則', 'knowledge/04-minibasket-diff'],
    ruleYear: 2026,
  },
  {
    id: 'ud-015',
    domain: 'u12-diff',
    roles: ['to-supporter', 'timer'],
    ruleset: 'u12',
    difficulty: 3,
    type: 'single',
    prompt: 'U12でゲームが没収（20対0）になるケースに当てはまらないのは？',
    choices: [
      'ゲーム開始15分を過ぎても5人揃わない',
      '出場義務条件を満たせなくなった',
      'タイムアウトを取りすぎた',
      'クルーチーフがすすめてもプレーを拒んだ',
    ],
    answer: 2,
    explanation:
      '没収の事由は「開始15分過ぎても5人揃わない」「出場義務を満たせない」「進行を妨げる行為」「プレー拒否」。タイムアウトの取りすぎという概念はない（残っていないチームの請求は審判を通じてコーチに伝えるだけ）。',
    refs: ['U12適用規則 第20条', 'knowledge/04-minibasket-diff'],
    ruleYear: 2026,
  },
]
